#### NOTIFICATIONS ####
# powiadomienie o dostępnej aktualizacji
- alias: Update Available Notification
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.html5
    data_template: 
      title: 'Nowa wersja Home Assistante'
      message: "Dostępna jest aktualizacja do wersji {{ states.updater.updater.state }} dla Home Assistant."
    data:
      data:
        tag: 'notification-hass-update'
        url: "{{ states.updater.updater.attributes.release_notes }}"

# powiadomienie o dostępnej aktualizacji dla routera
- alias: Router Update Available Notification
  trigger:
    platform: state
    entity_id: sensor.router_update
  action:
    service: notify.html5
    data_template: 
      title: 'Nowa wersja oprogramowania routera'
      message: "Dostępna jest aktualizacja oprogramowania routera do wersji {{ states.sensor.router_update.state }}."
    data:
      data:
        tag: 'notification-router-update'
        url: "https://asuswrt.lostrealm.ca/changelog"

# powiadomienia o małej ilości miejsca na Synology
- alias: Low Disk Space On Synology Notification
  trigger:
    platform: numeric_state
    entity_id: sensor.synology_disk_used
    above: 70
  action:
    service: notify.html5
    data_template: 
      title: 'Mało miejsca na sysku Synology'
      message: "Dysk Synology jest zajęty w {{ states.sensor.synology_disk_used.state }}%."
    data:
      data:
        tag: 'notification-synology-low-disk'
        url: !secret synology_http

# powiadomienie o wykryciu nowego urządzenia
- alias: New Device Notification
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    service: notify.html5
    data_template:
      title: 'Nowe urządzenie'
      message: "Wykryto nowe urządzenie sieciowe lub Bluetooth."
    data:
      data:
        tag: 'notification-new-device'

# niski poziom baterii
- alias: 'Low Battery Alert'
  trigger:
    platform: time
    after: '18:00:00'
  condition:
    condition: template
    value_template: >-
       {% for entity_id in states.group.batteries.attributes.entity_id if states(entity_id) | int < 15 %}
       {%- if loop.first -%}
       {{ true }}
       {%- endif -%}
       {% endfor %}
  action:
    service: notify.html5
    data_template:
      title: 'Niski poziom naładowania baterii'
      message: "Wykryto niski poziom naładowania baterii w przynajmniej jednym urządzeniu."
    data:
      data:
        tag: 'notification-low-battery'

#### PRESENCE ####
# Edyta 40 minut od domu
- alias: 'Edyta Far From Home'
  trigger:
    platform: template
    value_template: "{{ (states.sensor.edyta_to_home.state != 'unknown') and (states.sensor.edyta_to_home.state | int > 40) }}"
  condition:
    condition: state
    entity_id: input_boolean.edyta_far_from_home
    state: 'off'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.edyta_far_from_home

# Maciek 40 minut od domu
- alias: 'Maciek Far From Home'
  trigger:
    platform: template
    value_template: "{{ (states.sensor.maciek_to_home.state != 'unknown') and (states.sensor.maciek_to_home.state | int > 40) }}"
  condition:
    condition: state
    entity_id: input_boolean.maciek_far_from_home
    state: 'off'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.maciek_far_from_home

# Maciek wrócił do domu
- alias: 'Maciek Come Back Home'
  trigger:
    platform: state
    entity_id: sensor.maciek_presence
    from: 'not_home'
    to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.maciek_far_from_home
    state: 'on'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.maciek_far_from_home

# Edyta wróciła do domu
- alias: 'Edyta Come Back Home'
  trigger:
    platform: state
    entity_id: sensor.edyta_presence
    from: 'not_home'
    to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.edyta_far_from_home
    state: 'on'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.edyta_far_from_home

#### HEATING ####
# zwiększenie temperatury rano w tygodniu jeśli ktoś jest w domu i trwa sezon grzewczy
- alias: Heating Day
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ (now().strftime("%s") | int | timestamp_custom("%H:%M")) == states.input_select.heating_night_end.state }}'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: input_boolean.heating_season
        state: 'on'
      - condition: state
        entity_id: group.peoples
        state: 'home'
  action:
    - service: climate.set_temperature
      entity_id: climate.antresola_thermostat_heating_1_2_1
      data_template:
        temperature: '{{ states.input_select.heating_temp_day.state }}'
    - service: climate.set_temperature
      entity_id: climate.salon_thermostat_heating_1_7_1
      data_template:
        temperature: '{{ states.input_select.heating_temp_day.state }}'
    - service: climate.set_temperature
      entity_id: climate.antek_thermostat_heating_1_3_1
      data_template:
        temperature: '{{ states.input_select.heating_temp_bedroom_day.state }}'
    - service: climate.set_temperature
      entity_id: climate.sypialnia_thermostat_heating_1_4_1
      data_template:
        temperature: '{{ states.input_select.heating_temp_bedroom_day.state }}'

# zmniejszenie temperatury na noc w tygodniu jeśli trwa sezon grzewczy
- alias: Heating Night
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ (now().strftime("%s") | int | timestamp_custom("%H:%M")) == states.input_select.heating_night_start.state }}'
      - condition: time
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
      - condition: state
        entity_id: input_boolean.heating_season
        state: 'on'
      - condition: state
        entity_id: input_boolean.party_mode
        state: 'off'
  action:
    - service: climate.set_temperature
      entity_id: climate.antresola_thermostat_heating_1_2_1
      data_template:
        temperature: '{{ states.input_select.heating_temp_night.state }}'
    - service: climate.set_temperature
      entity_id: climate.salon_thermostat_heating_1_7_1
      data_template:
        temperature: '{{ states.input_select.heating_temp_night.state }}'
    - service: climate.set_temperature
      entity_id: climate.antek_thermostat_heating_1_3_1
      data_template:
        temperature: '{{ states.input_select.heating_temp_bedroom_night.state }}'
    - service: climate.set_temperature
      entity_id: climate.sypialnia_thermostat_heating_1_4_1
      data_template:
        temperature: '{{ states.input_select.heating_temp_bedroom_night.state }}'

# zwiększenie temperatury rano w weekendy jeśli ktoś jest w domu i trwa sezon grzewczy
- alias: Heating Day Weekend
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ (now().strftime("%s") | int | timestamp_custom("%H:%M")) == states.input_select.heating_night_end_weekend.state }}'
      - condition: time
        weekday:
          - sat
          - sun
      - condition: state
        entity_id: input_boolean.heating_season
        state: 'on'
      - condition: state
        entity_id: group.peoples
        state: 'home'
  action:
    service: automation.trigger
    entity_id: automation.heating_day

# zmniejszenie temperatury na noc w weekendy jeśli trwa sezon grzewczy
- alias: Heating Night Weekend
  trigger:
    platform: time
    minutes: '/1'
    seconds: 0
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ (now().strftime("%s") | int | timestamp_custom("%H:%M")) == states.input_select.heating_night_start_weekend.state }}'
      - condition: time
        weekday:
          - fri
          - sat
      - condition: state
        entity_id: input_boolean.heating_season
        state: 'on'
      - condition: state
        entity_id: input_boolean.party_mode
        state: 'off'
  action:
    service: automation.trigger
    entity_id: automation.heating_night

# zmniejszenie temperatury na noc po imprezie
- alias: Heating Night After Party
  trigger:
    platform: state
    entity_id: media_player.denon
    state: 'off'
  condition:
    condition: state
    entity_id: input_boolean.party_mode
    state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.party_mode
    - condition: state
      entity_id: input_boolean.heating_season
      state: 'on'
    - delay: 0:15
    - service: automation.trigger
      entity_id: automation.heating_night

# zmniejszenie temperatury gdy domownicy wychodzą i jest sezon grzewczy
- alias: Heating Peoples Away
  trigger:
    platform: state
    entity_id: group.peoples
    from: 'home'
    to: 'not_home'
    for:
      minutes: 20
  condition:
    condition: state
    entity_id: input_boolean.heating_season
    state: 'on'
  action:
    - service: climate.set_temperature
      entity_id: climate.antresola_thermostat_heating_1_2_1
      data_template:
        temperature: '{{ states.input_select.heating_temp_eco.state }}'
    - service: climate.set_temperature
      entity_id: climate.salon_thermostat_heating_1_7_1
      data_template:
        temperature: '{{ states.input_select.heating_temp_eco.state }}'
    - service: climate.set_temperature
      entity_id: climate.antek_thermostat_heating_1_3_1
      data_template:
        temperature: '{{ states.input_select.heating_temp_eco.state }}'
    - service: climate.set_temperature
      entity_id: climate.sypialnia_thermostat_heating_1_4_1
      data_template:
        temperature: '{{ states.input_select.heating_temp_eco.state }}'
    - service: input_boolean.turn_on
      entity_id: input_boolean.heating_away_mode

# zwiększenie temperatury gdy domownicy wracają i jest sezon grzewczy
- alias: Heating Peoples Back
  trigger:
    platform: state
    entity_id: group.peoples
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '05:30:00'
        before: '22:00:00'
      - condition: state
        entity_id: input_boolean.heating_season
        state: 'on'
      - condition: state
        entity_id: input_boolean.heating_away_mode
        state: 'on'
  action:
    - service: automation.trigger
      entity_id: automation.heating_day
    - service: input_boolean.turn_off
      entity_id: input_boolean.heating_away_mode

- alias: Heating Peoples Back Night
  trigger:
    platform: state
    entity_id: group.peoples
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '22:00:00'
        before: '05:30:00'
      - condition: state
        entity_id: input_boolean.heating_season
        state: 'on'
      - condition: state
        entity_id: input_boolean.heating_away_mode
        state: 'on'
  action:
    - service: automation.trigger
      entity_id: automation.heating_night
    - service: input_boolean.turn_off
      entity_id: input_boolean.heating_away_mode

# włączenie ogrzewania 30 minut przed powrotem do domu w dzień gdy jest sezon grzewczy
- alias: Turn On Heating Before Return To Home
  trigger:
    platform: template
    value_template: "{{ ((states.sensor.maciek_to_home.state != 'unknown') and (states.sensor.edyta_to_home.state != 'unknown')) and ((states.sensor.maciek_to_home.state | int < 30) or (states.sensor.edyta_to_home.state | int < 30)) }}"
  condition:
    condition: and
    conditions:
      - condition: time
        after: '05:30:00'
        before: '23:00:00'
      - condition: state
        entity_id: group.peoples
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.edyta_far_from_home
        state: 'on'
      - condition: state
        entity_id: input_boolean.maciek_far_from_home
        state: 'on'
      - condition: state
        entity_id: input_boolean.heating_season
        state: 'on'
      - condition: state
        entity_id: input_boolean.heating_away_mode
        state: 'on'
  action:
    - service: automation.trigger
      entity_id: automation.heating_day
    - service: input_boolean.turn_off
      entity_id: input_boolean.edyta_far_from_home
    - service: input_boolean.turn_off
      entity_id: input_boolean.maciek_far_from_home
    - service: input_boolean.turn_off
      entity_id: input_boolean.heating_away_mode

# początek sezonu grzewczego
- alias: Heating Season Begin
  trigger:
    platform: state
    entity_id: input_boolean.heating_season
    from: 'off'
    to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id:
        - automation.heating_day_weekend
        - automation.heating_day_working_day
        - automation.heating_night_weekend
        - automation.heating_night_working_day
        - automation.heating_peoples_away
        - automation.heating_peoples_back
        - automation.heating_peoples_back_night
        - automation.turn_on_heating_before_return_to_home
        - automation.salon_thermostat_setpoint_change
        - automation.kuchnia_thermostat_setpoint_change
    - service: automation.trigger
      entity_id: automation.heating_day

# koniec sezonu grzewczego
- alias: Heating Season End
  trigger:
    platform: state
    entity_id: input_boolean.heating_season
    from: 'on'
    to: 'off'
  action:
    - service: climate.set_temperature
      entity_id: climate.antresola_thermostat_heating_1_2_1
      data:
        temperature: 4
    - service: climate.set_temperature
      entity_id: climate.salon_thermostat_heating_1_7_1
      data:
        temperature: 4
    - service: climate.set_temperature
      entity_id: climate.kuchnia_thermostat_heating_1_5_1
      data:
        temperature: 4
    - service: climate.set_temperature
      entity_id: climate.antek_thermostat_heating_1_3_1
      data:
        temperature: 4
    - service: climate.set_temperature
      entity_id: climate.sypialnia_thermostat_heating_1_4_1
      data:
        temperature: 4
    - service: homeassistant.turn_off
      entity_id:
        - automation.heating_day_weekend
        - automation.heating_day_working_day
        - automation.heating_night_weekend
        - automation.heating_night_working_day
        - automation.heating_peoples_away
        - automation.heating_peoples_back
        - automation.heating_peoples_back_night
        - automation.turn_on_heating_before_return_to_home
        - automation.salon_thermostat_setpoint_change
        - automation.kuchnia_thermostat_setpoint_change

# ustawia w kuchni temperaturę z salonu
- alias: "Salon Thermostat SetPoint Change"
  trigger:
    platform: state
    entity_id: climate.salon_thermostat_heating_1_7_1
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >-
           {% if (trigger.to_state and trigger.from_state) %}
              {{ trigger.to_state.attributes.temperature != trigger.from_state.attributes.temperature }}
           {% endif %}
      - condition: template
        value_template: >-
           {% if (trigger.to_state and states.climate.kuchnia_thermostat_heating_1_5_1) %}
              {{ trigger.to_state.attributes.temperature != states.climate.kuchnia_thermostat_heating_1_5_1.attributes.temperature }}
           {% endif %}
  action:
    service: climate.set_temperature
    entity_id: climate.kuchnia_thermostat_heating_1_5_1
    data_template:
      temperature: '{{ trigger.to_state.attributes.temperature }}'

# ustawia w salonie temperaturę z kuchni
- alias: "Kuchnia Thermostat SetPoint Change"
  trigger:
    platform: state
    entity_id: climate.kuchnia_thermostat_heating_1_5_1
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: >-
           {% if (trigger.to_state and trigger.from_state) %}
              {{ trigger.to_state.attributes.temperature != trigger.from_state.attributes.temperature }}
           {% endif %}
      - condition: template
        value_template: >-
           {% if (trigger.to_state and states.climate.salon_thermostat_heating_1_7_1) %}
              {{ trigger.to_state.attributes.temperature != states.climate.salon_thermostat_heating_1_7_1.attributes.temperature }}
           {% endif %}
  action:
    service: climate.set_temperature
    entity_id: climate.salon_thermostat_heating_1_7_1
    data_template:
      temperature: '{{ trigger.to_state.attributes.temperature }}'

#### LIGHT ####
# włączenie trybu imprezoweg oświetlenia
- alias: "Lights Disco Mode Begin"
  trigger: 
    platform: time
    seconds: '/5'
  condition: 
    condition: state
    entity_id: input_boolean.disco_mode
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.gateway_light_f0b429cc6f0b
    data_template:
      brightness: 60
      rgb_color: ['{{ (range(0, 255)|random) }}','{{ (range(0, 255)|random) }}','{{ (range(0, 255)|random) }}']

- alias: "Lights Disco Mode End"
  trigger: 
    platform: state
    entity_id: input_boolean.disco_mode
    from: 'on'
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.gateway_light_f0b429cc6f0b