- platform: ping
  host: !secret router_hostname
  name: router_status
  count: 2
  scan_interval: 180

- platform: ping
  host: !secret modem_hostname
  name: modem_status
  count: 2
  scan_interval: 180
