- platform: template
  sensors:
    gaming:
      entity_id: sensor.androidtv_activity
      value_template: >-
         {% for game in ["GT Racing 2","CrossyRoad","Rayman Adventures","BADLAND","Fast like a Fox","BB Racing","Red Ball 4","Sky Force","Minion Rush","Superfrog HD","Leo's Fortune","Rayman Fiesta Run","Minecraft","Riptide GP: Renegade"] %}
            {% if game == states.sensor.androidtv_activity.state %}
               True
            {% endif %}
         {% endfor %}