- platform: ping
  host: !secret router_hostname
  name: router_status
  count: 2
  scan_interval: 180

- platform: ping
  host: !secret modem_hostname
  name: modem_status
  count: 2
  scan_interval: 180

- platform: workday
  country: "PL"

- platform: template
  sensors:
    people_at_home:
      value_template: >-
        {{ is_state('group.household', 'home')
           or is_state('group.family', 'home')
           or is_state('media_player.denon_salon', 'on')
           or is_state('input_boolean.guests', 'on') }}

    windows:
      friendly_name: "Okna"
      device_class: "window"
      value_template: >-
        {{ is_state('binary_sensor.window_antek', 'on')
           or is_state('binary_sensor.window_antresola_1', 'on')
           or is_state('binary_sensor.window_antresola_2', 'on')
           or is_state('binary_sensor.window_gabinet', 'on')
           or is_state('binary_sensor.window_kuchnia', 'on')
           or is_state('binary_sensor.window_salon', 'on')
           or is_state('binary_sensor.window_sypialnia', 'on')
           or is_state('binary_sensor.balcony_door_pracownia', 'on')
           or is_state('binary_sensor.balcony_door_sypialnia', 'on') }}

    windows_antresola:
      friendly_name: "Okna"
      device_class: "window"
      value_template: >-
        {{ is_state('binary_sensor.window_antresola_1', 'on')
            or is_state('binary_sensor.window_antresola_2', 'on') }}

    motion_antresola:
      friendly_name: "Ruch"
      device_class: "motion"
      value_template: >-
        {{ is_state('binary_sensor.motion_antresola_2', 'on')
           or is_state('binary_sensor.motion_antresola_1', 'on') }}

    motion_salon:
      friendly_name: "Ruch"
      device_class: "motion"
      value_template: >-
        {{ is_state('binary_sensor.motion_salon_1', 'on')
           or is_state('binary_sensor.motion_salon_2', 'on') }}

    access_point_status:
      value_template: "{{ is_state('device_tracker.access_point', 'home') }}"
      friendly_name: "Asus RT-AC68U"

    synology_status:
      value_template: "{{ is_state('device_tracker.synology', 'home') }}"
      friendly_name: "Synology DS110j"

    nuc_status:
      value_template: "{{ is_state('device_tracker.intel_nuc', 'home') }}"
      friendly_name: "Intel NUC 5CPYH"

    raspberry_status:
      value_template: "{{ is_state('device_tracker.raspberry', 'home') }}"
      friendly_name: "Raspberry Pi 4B"

    stacjonarny_status:
      value_template: "{{ is_state('device_tracker.stacjonarny', 'home') }}"
      friendly_name: "Komputer stacjonarny"

    dune_status:
      value_template: "{{ is_state('device_tracker.dune', 'home') }}"
      friendly_name: "Dune BD Prime 3.0"

    bravia_status:
      value_template: "{{ is_state('device_tracker.bravia', 'home') }}"
      friendly_name: "Sony KD-55XF8596"

    xbox_status:
      value_template: "{{ is_state('device_tracker.xbox', 'home') }}"
      friendly_name: "Xbox360"

    playstation_status:
      value_template: "{{ is_state('device_tracker.playstation', 'home') }}"
      friendly_name: "PlayStation 4 Pro"

    fingbox_status:
      value_template: "{{ is_state('device_tracker.fingbox', 'home') }}"
      friendly_name: "Fingbox"

    harmonyhub_status:
      value_template: "{{ is_state('device_tracker.harmonyhub', 'home') }}"
      friendly_name: "Logitech Harmony Hub"

    oneplus_status:
      value_template: "{{ is_state('device_tracker.oneplus_6', 'home') }}"
      friendly_name: "OnePlus 6"

    iphone_8_plus_status:
      value_template: "{{ is_state('device_tracker.iphone_8_plus', 'home') }}"
      friendly_name: "iPhone 8 Plus"

    iphone_11_status:
      value_template: "{{ is_state('device_tracker.iphone_11', 'home') }}"
      friendly_name: "iPhone 11"

    ipad_status:
      value_template: "{{ is_state('device_tracker.ipad_air', 'home') }}"
      friendly_name: "iPad Air"

    kindle_status:
      value_template: "{{ is_state('device_tracker.kindle', 'home') }}"
      friendly_name: "Kindle Keyboard 3G"

    kindle_8_status:
      value_template: "{{ is_state('device_tracker.kindle_8', 'home') }}"
      friendly_name: "Kindle 8"

    echo_plus_status:
      value_template: "{{ is_state('device_tracker.echo_plus', 'home') }}"
      friendly_name: "Amazon Echo Plus"

    echo_show_status:
      value_template: "{{ is_state('device_tracker.echo_show', 'home') }}"
      friendly_name: "Amazon Echo Show"

    echo_dot_status:
      value_template: "{{ is_state('device_tracker.echo_dot', 'home') }}"
      friendly_name: "Amazon Echo Dot"

    inkbook_status:
      value_template: "{{ is_state('device_tracker.inkbook', 'home') }}"
      friendly_name: "inkBook Classic 2"

    lumia_status:
      value_template: "{{ is_state('device_tracker.lumia_640', 'home') }}"
      friendly_name: "Lumia 640"

    mibox_status:
      value_template: "{{ is_state('device_tracker.mibox', 'home') }}"
      friendly_name: "Xiaomi Mi Box 3"

    firetv_status:
      value_template: "{{ is_state('device_tracker.firetv', 'home') }}"
      friendly_name: "Fire TV Stick 4K"

    laptop_edyta_status:
      value_template: "{{ is_state('device_tracker.laptop_edyta', 'home') }}"
      friendly_name: "Dell Latitude 7290"

    laptop_antek_status:
      value_template: "{{ is_state('device_tracker.laptop_antek', 'home') }}"
      friendly_name: "Lenovo IdeaPad S145"

    denon_status:
      value_template: "{{ is_state('device_tracker.denon', 'home') }}"
      friendly_name: "Denon AVR-X2100W"

    laptop_status:
      value_template: "{{ is_state('device_tracker.laptop', 'home') }}"
      friendly_name: "Lenovo IdeaPad Z510"

    migateway_cc6f0b_status:
      value_template: "{{ is_state('device_tracker.migateway_cc6f0b', 'home') }}"
      friendly_name: "Xiaomi Mi Gateway 2 [CC6F0B]"

    migateway_a0f210_status:
      value_template: "{{ is_state('device_tracker.migateway_a0f210', 'home') }}"
      friendly_name: "Xiaomi Mi Gateway 2 [A0F210]"

    mihumidifier_status:
      value_template: "{{ is_state('device_tracker.mihumidifier', 'home') }}"
      friendly_name: "Xiaomi Mi Humidifier CA1"

    miairpurifier_status:
      value_template: "{{ is_state('device_tracker.miairpurifier', 'home') }}"
      friendly_name: "Xiaomi Mi Air Purifier 3H"

    mifan_status:
      value_template: "{{ is_state('device_tracker.mifan', 'home') }}"
      friendly_name: "Xiaomi Mi Pedestal Fan 1X"

    brother_status:
      value_template: "{{ is_state('device_tracker.brother', 'home') }}"
      friendly_name: "Brother HL-L2340DW"

    dafang_status:
      value_template: "{{ is_state('device_tracker.dafang', 'home') }}"
      friendly_name: "Xiaomi DaFang"

    sonoff_basic_a786cc_status:
      friendly_name: "Sonoff Basic [A786CC]"
      value_template: "{{ is_state('device_tracker.sonoff_basic_a786cc', 'home') }}"

    sonoff_basic_067c81_status:
      friendly_name: "Sonoff Basic [067C81]"
      value_template: "{{ is_state('device_tracker.sonoff_basic_067c81', 'home') }}"

    sonoff_basic_5dfba8_status:
      friendly_name: "Sonoff Basic [5DFBA8]"
      value_template: "{{ is_state('device_tracker.sonoff_basic_5dfba8', 'home') }}"

    sonoff_s26_182475_status:
      friendly_name: "Sonoff S26 [182475]"
      value_template: "{{ is_state('device_tracker.sonoff_s26_182475', 'home') }}"

    blitzwolf_bw_shp6_2ad05a_status:
      friendly_name: "BlitzWolf BW-SHP6 [2AD05A]"
      value_template: "{{ is_state('device_tracker.blitzwolf_bw_shp6_2ad05a', 'home') }}"

    blitzwolf_bw_shp6_173eb6_status:
      friendly_name: "BlitzWolf BW-SHP6 [173EB6]"
      value_template: "{{ is_state('device_tracker.blitzwolf_bw_shp6_173eb6', 'home') }}"

    blitzwolf_bw_shp6_17957c_status:
      friendly_name: "BlitzWolf BW-SHP6 [17957C]"
      value_template: "{{ is_state('device_tracker.blitzwolf_bw_shp6_17957c', 'home') }}"

    blitzwolf_bw_shp6_3766eb_status:
      friendly_name: "BlitzWolf BW-SHP6 [3766EB]"
      value_template: "{{ is_state('device_tracker.blitzwolf_bw_shp6_3766eb', 'home') }}"

    blitzwolf_bw_shp6_ecf9ea_status:
      friendly_name: "BlitzWolf BW-SHP6 [ECF9EA]"
      value_template: "{{ is_state('device_tracker.blitzwolf_bw_shp6_ecf9ea', 'home') }}"

    blitzwolf_bw_shp6_ed007d_status:
      friendly_name: "BlitzWolf BW-SHP6 [ED007D]"
      value_template: "{{ is_state('device_tracker.blitzwolf_bw_shp6_ed007d', 'home') }}"

    shelly_1_328900_status:
      friendly_name: "Shelly 1 [328900]"
      value_template: "{{ is_state('device_tracker.shelly_1_328900', 'home') }}"

    shelly_1l_ad365e_status:
      friendly_name: "Shelly 1L [AD365E]"
      value_template: "{{ is_state('device_tracker.shelly_1l_ad365e', 'home') }}"

    shelly_1l_701559_status:
      friendly_name: "Shelly 1L [701559]"
      value_template: "{{ is_state('device_tracker.shelly_1l_701559', 'home') }}"

    shelly_1l_acedf2_status:
      friendly_name: "Shelly 1L [ACEDF2]"
      value_template: "{{ is_state('device_tracker.shelly_1l_acedf2', 'home') }}"

    shelly_1l_61c9fd_status:
      friendly_name: "Shelly 1L [61C9FD]"
      value_template: "{{ is_state('device_tracker.shelly_1l_61c9fd', 'home') }}"

    shelly_1l_aceb5f_status:
      friendly_name: "Shelly 1L [ACEB5F]"
      value_template: "{{ is_state('device_tracker.shelly_1l_aceb5f', 'home') }}"

    shelly_1l_ad1b60_status:
      friendly_name: "Shelly 1L [AD1B60]"
      value_template: "{{ is_state('device_tracker.shelly_1l_ad1b60', 'home') }}"

    shelly_2_5b2604_status:
      friendly_name: "Shelly 2 [5B2604]"
      value_template: "{{ is_state('device_tracker.shelly_2_5b2604', 'home') }}"

    shelly_plug_s_7aecf4_status:
      friendly_name: "Shelly Plug S [7AECF4]"
      value_template: "{{ is_state('device_tracker.shelly_plug_s_7aecf4', 'home') }}"

    shelly_ht_e00abd_status:
      friendly_name: "Shelly H&T [E00ABD]"
      value_template: "{{ is_state('device_tracker.shelly_ht_e00abd', 'home') }}"

    shelly_flood_f2ad1d_status:
      friendly_name: "Shelly Flood [F2AD1D]"
      value_template: "{{ is_state('device_tracker.shelly_flood_f2ad1d', 'home') }}"

    shelly_motion_97664e_status:
      friendly_name: "Shelly Motion [97664E]"
      value_template: "{{ is_state('device_tracker.shelly_motion_97664e', 'home') }}"

    wemos_d1_mini_1c91ea_status:
      friendly_name: "Wemos D1 mini [1C91EA]"
      value_template: "{{ is_state('device_tracker.wemos_d1_mini_1c91ea', 'home') }}"

    yeelight_mjtd01syl_94e1f5_status:
      friendly_name: "Xiaomi Mi Led Desk Lamp 1S [94E1F5]"
      value_template: "{{ is_state('device_tracker.yeelight_mjtd01syl_94e1f5', 'home') }}"

    yeelight_mjtd01syl_4fbaa2_status:
      friendly_name: "Xiaomi Mi Led Desk Lamp 1S [4FBAA2]"
      value_template: "{{ is_state('device_tracker.yeelight_mjtd01syl_4fbaa2', 'home') }}"

    yeelight_yldp06yl_7cafc6_status:
      friendly_name: "Yeelight YLDP06YL [7CAFC6]"
      value_template: "{{ is_state('device_tracker.yeelight_yldp06yl_7cafc6', 'home') }}"

    yeelight_yldp06yl_84be7a_status:
      friendly_name: "Yeelight YLDP06YL [84BE7A]"
      value_template: "{{ is_state('device_tracker.yeelight_yldp06yl_84be7a', 'home') }}"

    yeelight_yldp02yl_b1b6aa_status:
      friendly_name: "Yeelight YLDP02YL [B1B6AA]"
      value_template: "{{ is_state('device_tracker.yeelight_yldp02yl_b1b6aa', 'home') }}"

    yeelight_yldp02yl_f12026_status:
      friendly_name: "Yeelight YLDP02YL [F12026]"
      value_template: "{{ is_state('device_tracker.yeelight_yldp02yl_f12026', 'home') }}"

    yeelight_yldd01yl_860cfa_status:
      friendly_name: "Yeelight YLDD01YL [860CFA]"
      value_template: "{{ is_state('device_tracker.yeelight_yldd01yl_860cfa', 'home') }}"

    yeelight_yldd01yl_6707fc_status:
      friendly_name: "Yeelight YLDD01YL [6707FC]"
      value_template: "{{ is_state('device_tracker.yeelight_yldd01yl_6707fc', 'home') }}"
