- platform: template
  sensors:
    gaming:
      entity_id: sensor.androidtv_activity
      value_template: >-
         {% for game in ["GT Racing 2","CrossyRoad","Rayman Adventures","BADLAND","Fast like a Fox","BB Racing","Red Ball 4","Sky Force","Minion Rush","Superfrog HD","Leo's Fortune","Rayman Fiesta Run","Minecraft","Riptide GP: Renegade"] %}
            {% if game == states.sensor.androidtv_activity.state %}
               True
            {% endif %}
         {% endfor %}

    people_at_home:
      entity_id:
        - device_tracker.maciek
        - device_tracker.maciek_gps_bt
        - device_tracker.edyta
        - device_tracker.edyta_iphone
        - device_tracker.agnieszka
        - device_tracker.emil
        - device_tracker.grazyna
        - device_tracker.jerzy
        - device_tracker.romana
        - media_player.denon
      value_template: >-
         {{ is_state('device_tracker.maciek', 'home')
            or is_state('device_tracker.maciek_gps_bt', 'home')
            or is_state('device_tracker.edyta', 'home')
            or is_state('device_tracker.edyta_iphone', 'home')
            or is_state('device_tracker.agnieszka', 'home')
            or is_state('device_tracker.emil', 'home')
            or is_state('device_tracker.grazyna', 'home')
            or is_state('device_tracker.jerzy', 'home')
            or is_state('device_tracker.romana', 'home')
            or is_state('media_player.denon', 'on') }}

    motion_antresola:
      entity_id:
        - binary_sensor.motion_sensor_158d000120a226
        - binary_sensor.motion_sensor_158d00014d0a27
      value_template: >-
         {{ is_state('binary_sensor.motion_sensor_158d000120a226', 'on')
            or is_state('binary_sensor.motion_sensor_158d00014d0a27', 'on') }}