- platform: generic_thermostat
  name: "Thermostat Lazienka"
  unique_id: thermostat_lazienka
  heater: switch.heater_lazienka
  target_sensor: sensor.temperature_lazienka
  min_temp: 5
  max_temp: 35
  min_cycle_duration:
    minutes: 10
  precision: 0.5
  hot_tolerance: 0.2

- platform: generic_thermostat
  name: "Thermostat Gabinet"
  unique_id: thermostat_gabinet
  heater: switch.heater_gabinet
  target_sensor: sensor.temperature_gabinet
  min_temp: 5
  max_temp: 35
  min_cycle_duration:
    minutes: 10
  precision: 0.5
  hot_tolerance: 0.2

- platform: generic_thermostat
  name: "Thermostat Goscinny"
  unique_id: thermostat_goscinny
  heater: switch.heater_goscinny
  target_sensor: sensor.temperature_goscinny
  min_temp: 5
  max_temp: 35
  min_cycle_duration:
    minutes: 10
  precision: 0.5
  hot_tolerance: 0.2
