automation: !include automations.yaml

binary_sensor: !include binary_sensors.yaml

climate:
  - platform: generic_thermostat
    name: "Custom Thermostat Lazienka"
    unique_id: thermostat_lazienka
    heater: switch.heater_lazienka
    target_sensor: sensor.temperature_lazienka
    min_temp: 4
    max_temp: 28
    min_cycle_duration:
      minutes: 10
    initial_hvac_mode: "heat"
    away_temp: 16
    precision: 0.5

default_config:

recorder:
  db_url: !secret mysql_db_url
  purge_keep_days: 7
  exclude:
    domains:
      - device_tracker

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

group: !include groups.yaml

history: !include history.yaml

homeassistant:
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies

logbook:
  exclude:
    domains:
      - device_tracker
      - script
    entity_globs:
      - binary_sensor.*_status
      - sensor.*_last_restart
      - sensor.*_last_boot
      - sensor.*_uptime

logger: !include logger.yaml

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/bom-weather-card/bom-weather-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module
    - url: /hacsfiles/home-assistant-sun-card/home-assistant-sun-card.js
      type: module
    - url: /hacsfiles/lovelace-canary/canary.js
      type: module

python_script:

scene: !include scenes.yaml

script: !include scripts.yaml

sensor: !include sensors.yaml

switch: !include switches.yaml

template: !include templates.yaml

shell_command:
  restart_shelly_devices: /config/scripts/restart_shelly_devices.sh
