automation: !include automations.yaml

climate: !include climate.yaml

default_config:

recorder:
  db_url: !secret mysql_db_url
  purge_keep_days: 7

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /hacsfiles/lovelace-canary/canary.js

group: !include groups.yaml

homeassistant:
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies

logbook:
  exclude:
    domains:
      - device_tracker
      - script
    entity_globs:
      - binary_sensor.*_status
      - sensor.*_last_restart
      - sensor.*_last_boot
      - sensor.*_uptime

logger: !include logger.yaml

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/home-assistant-sun-card/home-assistant-sun-card.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
                

python_script:

scene: !include scenes.yaml

script: !include scripts.yaml

sensor: !include sensors.yaml

switch: !include switches.yaml

fan: !include fans.yaml

template: !include templates.yaml

panel_custom:
  - name: zha_map
    sidebar_title: Zigbee
    sidebar_icon: mdi:zigbee
    js_url: /api/hassio/app/entrypoint.js
    url_path: config/zha/visualization?config_entry=f9ae1510a963b99ee5fba82bf62904ae
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

weather:
  - platform: template
    name: "Home"
    unique_id: "home"
    condition_template: "{{ states('weather.accuweather') }}"
    temperature_template: "{{ (states('sensor.temperature_outdoor') or state_attr('weather.accuweather', 'temperature')) | float }}"
    humidity_template: "{{ (states('sensor.humidity_outdoor') or state_attr('weather.accuweather', 'humidity')) | float }}"
    pressure_template: "{{ (states('sensor.pressure_outdoor', rounded=True) or state_attr('weather.accuweather', 'pressure')) | float }}"
    dew_point_template: "{{ state_attr('weather.accuweather', 'dew_point') }}"
    apparent_temperature_template: "{{ state_attr('weather.accuweather', 'apparent_temperature') }}"
    wind_speed_template: "{{ state_attr('weather.accuweather', 'wind_speed') }}"
    wind_bearing_template: "{{ state_attr('weather.accuweather', 'wind_bearing') }}"
    wind_gust_speed_template: "{{ state_attr('weather.accuweather', 'wind_gust_speed') }}"
    visibility_template: "{{ state_attr('weather.accuweather', 'visibility') }}"
    cloud_coverage_template: "{{ state_attr('weather.accuweather', 'cloud_coverage') }}"
    forecast_template: "{{ state_attr('weather.openweathermap', 'forecast') }}"
    
proximity:
  edyta_home:
    ignored_zones:
      - zone.grandmother
      - zone.grandparents
      - zone.school_antek
      - zone.skaratki_horses
      - zone.work_edyta_lodz
      - zone.work_edyta_warszawa
    devices:
      - person.edyta
    tolerance: 50
    unit_of_measurement: km