homeassistant:
  name: home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 97
  unit_system: metric
  time_zone: Europe/Warsaw
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

zone:
  name: work
  icon: mdi:domain
  latitude: 52.1344
  longitude: 21.0586

zone 2:
  name: work
  icon: mdi:domain
  latitude: 52.2316
  longitude: 21.0013

zone 3:
  name: work
  icon: mdi:domain
  latitude: 51.7539
  longitude: 19.4559

frontend:
  javascript_version: latest

map:

http:
  api_password: !secret api_password
  ip_ban_enabled: true
  login_attempts_threshold: 5
  base_url: !secret http_base_url

recorder:
#  purge_interval: 4
#  purge_keep_days: 2
  exclude:
    domains:
      - automation
      - updater
      - sun
      - scenes
      - script
      - groups
      - mqtt
      - device_tracker
    entities:
      - sensor.printer_toner_status
      - sensor.sunset
      - sensor.sunrise
      - sensor.sun_custom
      - sensor.ssl_certificate_expiry
      - sensor.androidtv_activity
      - sensor.dune_activity
      - binary_sensor.switch_158d000154964c
      - binary_sensor.switch_158d00014a0911
      - input_number.gaming_end_hours
      - input_number.gaming_end_minutes
      - input_boolean.gaming_timer
      - binary_sensor.gaming
      - sensor.ha_version_current
      - sensor.ha_version_installed
      - input_boolean.harmony_command
      - sensor.uptime
      - sensor.temperature_158d0001826f20
      - sensor.temperature_158d00010fb340
      - sensor.temperature_158d0001100416
      - sensor.temperature_158d00010fb2cd
      - sensor.temperature_158d000129a158
      - sensor.temperature_158d000149cc8c
      - sensor.humidity_158d00010fb340
      - sensor.humidity_158d0001826f20
      - sensor.humidity_158d0001100416
      - sensor.humidity_158d00010fb2cd
      - sensor.humidity_158d000129a158
      - sensor.humidity_158d000149cc8c
  include:
    entities:
      - group.family
      - group.peoples
      - device_tracker.grazyna
      - device_tracker.jerzy
      - device_tracker.romana
      - device_tracker.agnieszka
      - device_tracker.emil
      - device_tracker.maciek_gps_bt
      - device_tracker.edyta_iphone

logger:
  default: warning
  logs:
    homeassistant.components.automation: info
    homeassistant.components.sensor.template: error
    homeassistant.components.sensor.snmp: fatal
    homeassistant.components.sensor.statistics: fatal
    homeassistant.components.zwave: info
    homeassistant.components.sensor: error
    pychromecast.socket_client: fatal
    homeassistant.helpers.entity: fatal
    homeassistant.components.sensor.darksky: fatal
    homeassistant.components.recorder: info
#    homeassistant.components.sensor.xiaomi_aqara: debug
#    homeassistant.components.xiaomi_aqara: debug
#    homeassistant.components.media_player: info
#    DenonAVR: info
#    homeassistant.components.device_tracker: debug
#    homeassistant.components.mqtt: debug
#    homeassistant.components.updater: debug

history:
  include:
    entities:
      - device_tracker.agnieszka
      - device_tracker.emil
      - device_tracker.grazyna
      - device_tracker.jerzy
      - group.peoples
      - sensor.edyta_presence
      - sensor.maciek_presence
      - sensor.dark_sky_humidity_custom
      - sensor.dark_sky_precip_probability_custom
      - sensor.dark_sky_pressure_custom
      - sensor.dark_sky_summary_custom
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_speed
      - sensor.ha_database_size
      - sensor.speedtest_download
      - sensor.speedtest_ping
      - sensor.speedtest_upload
      - sensor.temperature_indoor
      - sensor.humidity_indoor
      - sensor.light_salon_energy
      - sensor.light_salon_energy_2

logbook:
  include:
    entities:
      - device_tracker.agnieszka
      - device_tracker.emil
      - device_tracker.grazyna
      - device_tracker.jerzy
      - group.peoples
      - sensor.edyta_presence
      - sensor.maciek_presence

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_select: !include input_select.yaml
shell_command: !include shell_command.yaml
device_tracker: !include device_tracker.yaml
media_player: !include media_player.yaml
switch: !include switches.yaml
light: !include lights.yaml

sun:

config:

#updater:
#  include_used_components: true

discovery:
  ignore:
    - denonavr
    - harmony

zeroconf:

ios:

zwave:
  usb_path: /dev/zwave
#  config_path: /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.3-py3.4-linux-armv7l.egg/config
  device_config: !include zwave_device_config.yaml

mqtt:
  broker: !secret mqtt_broker_ip
  port: !secret mqtt_broker_port
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

xiaomi_aqara:
  gateways:
    mac: !secret xiaomi_gateway_mac
    key: !secret xiaomi_gateway_key

notify:
  - platform: html5
    name: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id
  - platform: nfandroidtv
    name: androidtv
    host: !secret androidtv_ip

input_boolean:
  heating_season:
    name: Sezon grzewczy
    icon: mdi:weather-snowy-rainy
  heating_salon_kuchnia_night:
  heating_night:
  heating_airing:
    name: Przewietrzanie
    icon: mdi:weather-windy
  edyta_far_from_home:
  maciek_far_from_home:
  away_mode:
    name: Poza domem
    icon: mdi:home-outline
  antresola_lamp_motion_on:
  salon_lamp_motion_on:
  sypialnia_lamp_motion_on:
  salon_light_scene_turn_on:
  gaming_timer:
    initial: 'off'
  harmony_command:
    initial: 'off'
  guests:
    name: Goście
    icon: mdi:account-multiple-outline

input_number:
  gaming_end_hours:
    min: 0
    max: 23
    step: 1
  gaming_end_minutes:
    min: 0
    max: 59
    step: 1

remote:
  - platform: harmony
    name: Salon
    host: !secret harmonyhub_ip

history_graph:
  power_consumption:
    name: Zużycie energii
    entities:
      - sensor.light_salon_power
      - sensor.light_salon_power_2
    hours_to_show: 48
    refresh: 60
  temperature:
    name: Temperatura
    entities:
      - sensor.temperature_indoor
      - sensor.dark_sky_temperature
    hours_to_show: 48
    refresh: 60
  humidity:
    name: Wilgotność
    entities:
      - sensor.humidity_indoor
      - sensor.dark_sky_humidity_custom
    hours_to_show: 48
    refresh: 60

python_script:

emulated_hue:
  expose_by_default: false
  exposed_domains:
    - switch
