homeassistant:
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

frontend:
  themes: !include_dir_merge_named themes

cloud:

zone:

logbook:
  exclude:
    domains:
      - device_tracker
      - zwave
      - script
    entity_globs:
      - binary_sensor.*_status
      - sensor.*_last_restart
      - sensor.*_last_boot
      - sensor.*_uptime

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/bom-weather-card/bom-weather-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module
    - url: /hacsfiles/lovelace-canary/canary.js
      type: module

person:

http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies

media_source:

recorder: !include recorder.yaml

logger: !include logger.yaml

history: !include history.yaml

system_health:

mobile_app:

updater:

stream:

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
media_player: !include media_player.yaml
switch: !include switches.yaml
light: !include lights.yaml

input_select: !include input_select.yaml
input_boolean:
input_number:
input_text:
input_datetime:

fan:
  - platform: xiaomi_miio_airpurifier
    name: Humidifier Salon
    model: zhimi.humidifier.ca1
    host: !secret humidifier_hostname
    token: !secret humidifier_token

  - platform: xiaomi_miio_airpurifier
    name: Air Purifier Salon
    model: zhimi.airpurifier.mb3
    host: !secret airpurifier_hostname
    token: !secret airpurifier_token
    retries: 2

  # - platform: xiaomi_miio_airpurifier
  #   model: dmaker.fan.p5
  #   host: !secret fan_hostname
  #   token: !secret fan_token

sun:

config:

ssdp:

zeroconf:

image:

counter:

timer:

zwave:
  debug: true

camera:
  - platform: generic
    name: 'Salon'
    still_image_url: !secret dafang_still_mage_url
    stream_source: !secret dafang_rtsp_url
    scan_interval: 5

python_script:

notify:
  - platform: nfandroidtv
    name: "MiBox"
    host: !secret mibox_hostname

  - platform: nfandroidtv
    name: "Bravia"
    host: !secret bravia_hostname

climate:
  - platform: generic_thermostat
    name: "Custom Thermostat Lazienka"
    unique_id: thermostat_lazienka
    heater: switch.heater_lazienka
    target_sensor: sensor.temperature_lazienka
    min_temp: 4
    max_temp: 28
    min_cycle_duration:
      minutes: 10
    initial_hvac_mode: "heat"
    away_temp: 16
    precision: 0.5

panel_custom:
  - name: zwave-graph-panel
    sidebar_title: "Mapa sieci Z-Wave"
    sidebar_icon: mdi:z-wave
    module_url: /local/zwavegraph.js
    config:
      ranker: network-simplex
      edge_visibility: relevant
      grouping: z-wave

device_tracker:
  - platform: traccar
    host: localhost
    port: 18682
    username: !secret traccar_email
    password: !secret traccar_password