homeassistant:
  name: home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 97
  unit_system: metric
  time_zone: Europe/Warsaw
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

zone:
  name: work
  icon: mdi:domain
  latitude: 52.1344
  longitude: 21.0586

zone 2:
  name: work
  icon: mdi:domain
  latitude: 52.2316
  longitude: 21.0013

zone 3:
  name: work
  icon: mdi:domain
  latitude: 51.7539
  longitude: 19.4559

frontend:

http:
  api_password: !secret api_password
  ip_ban_enabled: true
  login_attempts_threshold: 5
  base_url: !secret http_base_url
  ssl_certificate: /etc/cert/cert.pem
  ssl_key: /etc/cert/cert.key

recorder:
  purge_days: 3
  exclude:
    domains:
      - automation
      - updater
      - sun
      - scenes
      - script
      - groups
    entities:
      - sensor.printer_toner_status
      - sensor.sunset
      - sensor.sunrise
      - sensor.sun_custom
      - sensor.ssl_certificate_expiry
      - sensor.androidtv_activity
      - sensor.dune_activity
      - binary_sensor.switch_158d000154964c
      - input_slider.gaming_end_hours
      - input_slider.gaming_end_minutes
      - input_boolean.gaming_timer
      - binary_sensor.gaming
      - sensor.ha_version_current
      - sensor.ha_version_installed
  include:
    entities:
      - group.family
      - group.peoples

logger:
  default: warning
  logs:
    homeassistant.components.automation: info
    homeassistant.components.sensor.template: error
    homeassistant.components.sensor.snmp: fatal
    homeassistant.components.sensor.statistics: error
    homeassistant.components.zwave: info
    homeassistant.components.sensor: error
    pychromecast.socket_client: fatal
    homeassistant.helpers.entity: fatal
#   homeassistant.components.media_player: info
#    DenonAVR: info
#    homeassistant.components.device_tracker: debug
#    homeassistant.components.mqtt: debug
#    homeassistant.components.updater: debug

history:
  include:
    entities:
      - device_tracker.agnieszka
      - device_tracker.emil
      - device_tracker.grazyna
      - device_tracker.jerzy
      - group.peoples
      - sensor.edyta_presence
      - sensor.maciek_presence
      - sensor.dark_sky_humidity_custom
      - sensor.dark_sky_precip_probability_custom
      - sensor.dark_sky_pressure_custom
      - sensor.dark_sky_summary_custom
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_speed
      - sensor.ha_database_size
      - sensor.speedtest_download
      - sensor.speedtest_ping
      - sensor.speedtest_upload
      - sensor.illumination_f0b429cc6f0b
      - sensor.temperature_indoor
      - sensor.humidity_indoor
      - sensor.light_salon_energy
      - sensor.light_salon_energy_2

logbook:
  include:
    entities:
      - device_tracker.agnieszka
      - device_tracker.emil
      - device_tracker.grazyna
      - device_tracker.jerzy
      - group.peoples
      - sensor.edyta_presence
      - sensor.maciek_presence

sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_select: !include input_select.yaml
shell_command: !include shell_command.yaml
device_tracker: !include device_tracker.yaml
media_player: !include media_player.yaml
switch: !include switches.yaml
light: !include lights.yaml

sun:

config:

updater:
  include_used_components: true

discovery:
  ignore:
    denonavr

zeroconf:

ios:

zwave:
  usb_path: /dev/zwave
#  config_path: /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.3-py3.4-linux-armv7l.egg/config
  device_config: !include zwave_device_config.yaml

mqtt:
  broker: !secret mqtt_broker_ip
  port: !secret mqtt_broker_port
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

xiaomi:
  gateways:
    mac: !secret xiaomi_gateway_mac
    key: !secret xiaomi_gateway_key
    poll_motion: false

notify:
  - platform: html5
    name: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id
  - platform: nfandroidtv
    name: androidtv
    host: !secret androidtv_ip

input_boolean:
  heating_season:
    name: Sezon grzewczy
    icon: mdi:weather-snowy-rainy
  heating_salon_kuchnia_night:
  heating_night:
  disco_mode:
    name: Dyskoteka
    icon: mdi:music
  heating_airing:
    name: Przewietrzanie
    icon: mdi:weather-windy
  edyta_far_from_home:
  maciek_far_from_home:
  away_mode:
  antresola_lamp_motion_on:
  salon_lamp_motion_on:
  salon_light_scene_turn_on:
  gaming_timer:
    initial: 'off'

input_slider:
  gaming_end_hours:
    min: 0
    max: 23
    step: 1
  gaming_end_minutes:
    min: 0
    max: 59
    step: 1

binary_sensor:
  - platform: template
    sensors:
      gaming:
        entity_id: sensor.androidtv_activity
        value_template: >-
           {% for game in ["GT Racing 2","CrossyRoad","Rayman Adventures","BADLAND","Fast like a Fox","BB Racing","Red Ball 4","Sky Force","Minion Rush","Superfrog HD","Leo's Fortune","Rayman Fiesta Run","Minecraft PE"] %}
              {% if game == states.sensor.androidtv_activity.state %}
                 True
              {% endif %}
           {% endfor %}

  - platform: trend
    sensors:
      temperature_salon_down:
        entity_id: sensor.temperature_158d00010fb340
        invert: Yes
      temperature_sypialnia_down:
        entity_id: sensor.temperature_158d0001100416
        invert: Yes
      temperature_pokoj_antek_down:
        entity_id: sensor.temperature_158d00010fb2cd
        invert: Yes
      temperature_antresola_down:
        entity_id: sensor.temperature_158d000149cc8c
        invert: Yes
