homeassistant:
  name: home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 97
  unit_system: metric
  time_zone: Europe/Warsaw
  customize: !include customize.yaml

zone:
  name: work
  icon: mdi:domain
  latitude: 52.1344
  longitude: 21.0586

zone 2:
  name: work
  icon: mdi:domain
  latitude: 52.2316
  longitude: 21.0013
  radius: 200

zone 3:
  name: work
  icon: mdi:domain
  latitude: 51.7539
  longitude: 19.4559
  radius: 250

sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automation.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_select:  !include input_select.yaml

frontend:

http:
  api_password: !secret api_password
  ip_ban_enabled: True
  login_attempts_threshold: 5
  base_url: !secret http_base_url
  ssl_certificate: /etc/cert/cert.pem
  ssl_key: /etc/cert/cert.key

updater:

#discovery:

zeroconf:

recorder:
  purge_days: 3
  exclude:
    domains:
      - automation
      - updater
      - sun

logger:
  default: warning
  logs:
    homeassistant.components.automation: info
    homeassistant.components.sensor.template: error
    DenonAVR: fatal
    pychromecast: fatal
    homeassistant.components.sensor.statistics: error
#    homeassistant.components.device_tracker: debug
#    homeassistant.components.media_player: debug
#    homeassistant.components.mqtt: debug
#    homeassistant.components.zwave: info

history:
  include:
    entities:
      - device_tracker.agnieszka
      - device_tracker.emil
      - device_tracker.grazyna
      - device_tracker.jerzy
      - group.bulbs_salon
      - group.peoples
      - light.gateway_light_f0b429cc6f0b
      - sensor.edyta_presence
      - sensor.maciek_presence
      - sensor.sun_custom
      - sensor.dark_sky_humidity_custom
      - sensor.dark_sky_precip_probability_custom
      - sensor.dark_sky_pressure_custom
      - sensor.dark_sky_summary_custom
      - sensor.dark_sky_temperature
      - sensor.dark_sky_wind_speed
      - sensor.ha_database_size
      - sensor.humidity_pokoj_antek
      - sensor.humidity_salon
      - sensor.humidity_sypialnia
      - sensor.speedtest_download
      - sensor.speedtest_ping
      - sensor.speedtest_upload
      - sensor.temperature_pokoj_antek
      - sensor.temperature_salon
      - sensor.temperature_sypialnia

logbook:
  include:
    entities:
      - device_tracker.agnieszka
      - device_tracker.emil
      - device_tracker.grazyna
      - device_tracker.jerzy
      - group.bulbs_salon
      - group.peoples
      - light.gateway_light_f0b429cc6f0b
      - sensor.edyta_presence
      - sensor.maciek_presence
      - sensor.sun_custom

sun:

config:

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.3-py3.4-linux-armv7l.egg/config
  device_config: !include zwave_device_config.yaml

mqtt:
  broker: !secret mqtt_broker_ip
  port: !secret mqtt_broker_port
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

climate:
  platform: zwave

xiaomi:
  gateways:
    sid: !secret xiaomi_gateway_sid
    key: !secret xiaomi_gateway_key

device_tracker:
  - platform: bluetooth_tracker
    interval_seconds: 60
    consider_home: 180
    track_new_devices: false
  - platform: asuswrt
    host: !secret router_ip
    username: !secret router_username
    password: !secret router_password
    protocol: ssh
  - platform: nmap_tracker
    hosts: 
      - !secret router_ip
      - !secret switch_ip
      - !secret lumia_ip
      - !secret synology_ip
    home_interval: 10
    scan_options: " --privileged -sP "
  - platform: gpslogger
  - platform: owntracks
    max_gps_accuracy: 1500
  - platform: ping
    hosts:
      modem: !secret modem_ip

media_player:
  - platform: denonavr
    host: !secret denon_ip
    name: Denon
#  - platform: spotify
#    client_id: !secret spotify_client_id
#    client_secret: !secret spotify_client_secret
#  - platform: cast
#    host: !secret androidtv_ip
#  - platform: dunehd
#    host: !secret dune_ip
#    name: Dune

notify:
  name: html5
  platform: html5
  gcm_api_key: !secret gcm_api_key
  gcm_sender_id: !secret gcm_sender_id

switch:
  platform: wake_on_lan
  name: wake_on_lan_stacjonarny
  host: !secret desktop_ip
  mac_address: !secret desktop_mac_address
  turn_off:
    service:
      shell_command.stacjonarny_off

shell_command:
  stacjonarny_off: "curl http://stacjonarny:88/event.html?Suspend"
  reboot_pi: "sudo reboot"
  shutdown_pi: "sudo shutdown -h now"
  restart_hass: "sudo systemctl restart home-assistant.service"
  reeboot_router: "echo 'reboot' | ssh maciek@router"

input_boolean:
  heating_season:
    name: Sezon grzewczy
    icon: mdi:weather-snowy-rainy
  party_mode:
    name: Impreza
    icon: mdi:emoticon-cool
  disco_mode:
    name: Dyskoteka
    icon: mdi:music
  heating_airing:
    name: Przewietrzanie
    icon: mdi:weather-windy
  edyta_far_from_home:
  maciek_far_from_home:
  away_mode:

light:
  platform: yeelight
  devices:
    192.168.1.240:
      name: yeelight color bulb salon 1
      transition: 500
      save_on_change: False
    192.168.1.250:
      name: yeelight color bulb salon 2
      transition: 500
      save_on_change: False

binary_sensor:
  - platform: trend
    sensors:
      temperature_salon_down:
        entity_id: sensor.temperature_158d00010fb340
        invert: Yes
      temperature_sypialnia_down:
        entity_id: sensor.temperature_158d0001100416
        invert: Yes
      temperature_pokoj_antek_down:
        entity_id: sensor.temperature_158d00010fb2cd
        invert: Yes
