homeassistant:
  name: 'Dom'
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 97
  unit_system: metric
  time_zone: Europe/Warsaw
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  whitelist_external_dirs: '/home/homeassistant/.homeassistant/www/snapshots'

frontend:
  javascript_version: auto
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml

person:

frontend_custom:

custom_updater:
  track:
    - cards
    - components
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/custom-cards/information/master/repos.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/iammexx/home-assistant-config/master/ui/darksky/version.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/MizterB/lovelace-secondaryinfo-entity-row/master/custom_cards.json
  python_script_urls:
    - https://raw.githubusercontent.com/bieniu/home-assistant-config/master/python_scripts/python_scripts.json
  component_urls:
    - https://raw.githubusercontent.com/custom-components/information/master/repos.json
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies: !secret synology_ip
  base_url: !secret http_base_url

recorder: !include recorder.yaml

logger: !include logger.yaml

history: !include history.yaml

system_health:

mobile_app:

utility_meter:
  energy_light_salon_monthly:
    source: sensor.energy_light_salon
    cycle: monthly

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_select: !include input_select.yaml
shell_command: !include shell_command.yaml
device_tracker: !include device_tracker.yaml
media_player: !include media_player.yaml
switch: !include switches.yaml
light: !include lights.yaml

fan:
  - platform: xiaomi_miio
    name: Humidifier Salon
    model: zhimi.humidifier.ca1
    host: !secret humidifier_hostname
    token: !secret humidifier_token

sun:

config:

discovery:
  ignore:
    - denonavr
    - harmony
    - yeelight
    - philips_hue
    - google_cast

zeroconf:

stream:

zwave:
  device_config: !include zwave_device_config.yaml
  debug: true

xiaomi_aqara:
  gateways:
    mac: !secret migateway_mac
    key: !secret migateway_key

camera:
  - platform: generic
    name: 'Salon'
    still_image_url: !secret dafang_still_mage_url
    stream_source: !secret dafang_rtsp_url
    scan_interval: 5

notify:
  - platform: html5
    name: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
    
input_boolean: !include input_boolean.yaml

panel_custom:
  - name: zwavegraph
    sidebar_title: Z-Wave
    sidebar_icon: mdi:z-wave
    url_path: zwave

remote:
  - platform: harmony
    name: Salon
    host: !secret harmonyhub_hostname

python_script:

emulated_hue: !include emulated_hue.yaml

yeelight:
  devices:
    192.168.2.249:
      name: 'bulb salon 1'
      model: 'color1'
      <<: &YEELIGHT_PARAMS
        transition: 500
        save_on_change: false
        use_music_mode: false
    192.168.2.251:
      name: 'bulb salon 2'
      model: 'color2'
      <<: *YEELIGHT_PARAMS
    192.168.2.250:
      name: 'lamp salon'
      model: 'color1'
      <<: *YEELIGHT_PARAMS
    192.168.2.253:
      name: 'lightstrip sypialnia'
      model: 'strip1'
      <<: *YEELIGHT_PARAMS
    192.168.2.254:
      name: 'lightstrip antek'
      model: 'strip1'
      <<: *YEELIGHT_PARAMS