homeassistant:
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  whitelist_external_dirs:
    - !secret snapshots_dir

frontend:
  themes: !include_dir_merge_named themes

cloud:

zone:

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/bom-weather-card/bom-weather-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-canary/canary.js
      type: module
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module
    - url: /local/cards/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
      type: module

person:

http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies
  base_url: !secret http_base_url

recorder: !include recorder.yaml

logger: !include logger.yaml

history: !include history.yaml

system_health:

mobile_app:

utility_meter:
  light_salon_energy_monthly:
    source: sensor.light_salon_energy
    cycle: monthly
  dishwasher_kuchnia_energy_monthly:
    source: sensor.dishwasher_kuchnia_energy
    cycle: monthly
  computer_gabinet_energy_monthly:
    source: sensor.computer_gabinet_energy
    cycle: monthly
  servers_gabinet_energy_monthly:
    source: sensor.servers_gabinet_energy
    cycle: monthly

sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
device_tracker: !include device_tracker.yaml
media_player: !include media_player.yaml
switch: !include switches.yaml
light: !include lights.yaml

input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_number:
input_text:
input_datetime:

fan:
  - platform: xiaomi_miio
    name: Humidifier Salon
    model: zhimi.humidifier.ca1
    host: !secret humidifier_hostname
    token: !secret humidifier_token

  - platform: xiaomi_miio_fan
    host: !secret fan_hostname
    token: !secret fan_token

sun:

config:

ssdp:

zeroconf:

zwave:
  device_config: !include zwave_device_config.yaml
  debug: true

xiaomi_aqara:
  gateways:
    mac: !secret migateway_mac
    key: !secret migateway_key

camera:
  - platform: generic
    name: 'Salon'
    still_image_url: !secret dafang_still_mage_url
    stream_source: !secret dafang_rtsp_url
    scan_interval: 5

notify:
  - platform: html5
    name: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

panel_custom:
  - name: zwavegraph
    sidebar_title: Z-Wave
    sidebar_icon: mdi:z-wave
    url_path: zwave
    require_admin: true

python_script:

yeelight:
  devices:
    yeelight-yldp02yl-b1b6aa.bieniu.lan:
      name: 'bulb antresola'
      model: 'color1'
      <<: &YEELIGHT_PARAMS
        transition: 500
        save_on_change: false
        use_music_mode: false
    yeelight-yldp02yl-f12026.bieniu.lan:
      name: 'lamp salon'
      model: 'color1'
      <<: *YEELIGHT_PARAMS
    yeelight-yldp06yl-84be7a.bieniu.lan:
      name: 'bulb salon 1'
      model: 'color2'
      <<: *YEELIGHT_PARAMS
    yeelight-yldp06yl-7cafc6.bieniu.lan:
      name: 'bulb salon 2'
      model: 'color2'
      <<: *YEELIGHT_PARAMS
    yeelight-yldd01yl-860cfa.bieniu.lan:
      name: 'lightstrip sypialnia'
      model: 'strip1'
      <<: *YEELIGHT_PARAMS
    yeelight-yldd01yl-6707fc.bieniu.lan:
      name: 'lightstrip antek'
      model: 'strip1'
      <<: *YEELIGHT_PARAMS
