automation: !include automations.yaml

binary_sensor: !include binary_sensors.yaml

camera:
  - platform: generic
    name: 'Salon'
    still_image_url: !secret dafang_still_mage_url
    stream_source: !secret dafang_rtsp_url
    scan_interval: 5

climate:
  - platform: generic_thermostat
    name: "Custom Thermostat Lazienka"
    unique_id: thermostat_lazienka
    heater: switch.heater_lazienka
    target_sensor: sensor.temperature_lazienka
    min_temp: 4
    max_temp: 28
    min_cycle_duration:
      minutes: 10
    initial_hvac_mode: "heat"
    away_temp: 16
    precision: 0.5

default_config:

device_tracker:
  - platform: traccar
    host: localhost
    port: 18682
    username: !secret traccar_email
    password: !secret traccar_password

fan: !include fans.yaml

frontend:
  themes: !include_dir_merge_named themes

group: !include groups.yaml

history: !include history.yaml

homeassistant:
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

http:
  ip_ban_enabled: true
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies

light: !include lights.yaml

logbook:
  exclude:
    domains:
      - device_tracker
      - script
    entity_globs:
      - binary_sensor.*_status
      - sensor.*_last_restart
      - sensor.*_last_boot
      - sensor.*_uptime

logger: !include logger.yaml

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/bom-weather-card/bom-weather-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module
    - url: /hacsfiles/home-assistant-sun-card/home-assistant-sun-card.js
      type: module
    - url: /hacsfiles/lovelace-canary/canary.js
      type: module

media_player: !include media_player.yaml

python_script:

recorder: !include recorder.yaml

scene: !include scenes.yaml

script: !include scripts.yaml

sensor: !include sensors.yaml

switch: !include switches.yaml

shell_command:
  restart_shelly_devices: /config/scripts/restart_shelly_devices.sh