- platform: nmap_tracker
  hosts: !secret lan_ip
  exclude: !secret nmap_exclude
  scan_options: " --privileged -sP "
  home_interval: 4
  interval_seconds: 60
  consider_home: 360
  new_device_defaults:
    track_new_devices: false
    hide_if_away: true

- platform: bluetooth_tracker

- platform: ping
  hosts:
    modem: !secret modem_hostname
    raspberry: !secret raspberry_hostname

- platform: iphonedetect
  hosts:
    ipad_air: !secret ipad_air_ip
    iphone_8_plus: !secret iphone_8_plus_ip