- platform: bluetooth_tracker
  interval_seconds: 60
  consider_home: 180
  track_new_devices: false
- platform: asuswrt
  host: !secret router_ip
  username: !secret router_username
  password: !secret router_password
  protocol: ssh
- platform: nmap_tracker
  hosts:
    - !secret lumia_ip
    - !secret migateway_ip
    - !secret brother_ip
  home_interval: 10
  scan_options: " --privileged -sP "
- platform: gpslogger
- platform: ping
  hosts:
    router: !secret router_ip
    modem: !secret modem_ip
    switch: !secret switch_ip
    denon: !secret denon_ip
    sonoff_lamp: !secret sonoff_lamp_ip
    sonoff_switch_single: !secret sonoff_switch_single_ip
    sonoff_switch_triple: !secret sonoff_switch_triple_ip
    synology: !secret synology_ip
