- platform: bluetooth_tracker
  interval_seconds: 60
  consider_home: 180
  new_device_defaults:
    track_new_devices: false
#  track_new_devices: false

- platform: asuswrt
  host: !secret router_hostname
  username: !secret router_username
  password: !secret router_password
  protocol: ssh

- platform: gpslogger

- platform: ping
  hosts:
    router: !secret router_hostname
    modem: !secret modem_hostname
    switch: !secret switch_hostname
    denon: !secret denon_hostname
