- platform: template
  fans:
    ceiling_salon:
      unique_id: "ceiling_salon"
      friendly_name: "Wentylator"
      value_template: >-
        {% if states("sensor.wentylator_i_oswietlenie_w_salonie_pobor_mocy") | int(0) >= 20 %}
          on
        {% else %}
          off
        {% endif %}
      percentage_template: >-
        {% set fan_power = states("sensor.wentylator_i_oswietlenie_w_salonie_pobor_mocy") | int(0) %}
        {% if fan_power >= 20 and fan_power <= 40 %}
          33
        {% elif fan_power >= 45 and fan_power <= 65 %}
          66
        {% elif fan_power >= 75 %}
          100
        {% else %}
          0
        {% endif %}
      turn_on:
        service: remote.send_command
        entity_id: remote.salon
        data:
          device: "Wentylator"
          command: "Speed 1"
      turn_off:
        service: remote.send_command
        entity_id: remote.salon
        data:
          device: "Wentylator"
          command: "Stop"
      set_percentage:
        service: remote.send_command
        entity_id: remote.salon
        data:
          device: "Wentylator"
          command: >-
            {% if percentage == 0 %}
              Stop
            {% elif percentage == 33 %}
              Speed 1
            {% elif percentage == 66 %}
              Speed 2
            {% elif percentage == 100 %}
              Speed 3
            {% endif %}
      speed_count: 3
