- platform: xiaomi_miio_airpurifier
  name: Humidifier Salon
  model: zhimi.humidifier.ca1
  host: !secret humidifier_hostname
  token: !secret humidifier_token

- platform: xiaomi_miio_airpurifier
  name: Air Purifier Salon
  model: zhimi.airpurifier.mb3
  host: !secret airpurifier_hostname
  token: !secret airpurifier_token
  retries: 2

# - platform: xiaomi_miio_airpurifier
#   model: dmaker.fan.p5
#   host: !secret fan_hostname
#   token: !secret fan_token