# - platform: xiaomi_miio_airpurifier
#   name: Air Purifier Salon
#   model: zhimi.airpurifier.mb3
#   host: !secret airpurifier_hostname
#   token: !secret airpurifier_token
#   retries: 2

- platform: xiaomi_miio_airpurifier
  name: "Pedestal Salon"
  model: dmaker.fan.p5
  host: !secret fan_hostname
  token: !secret fan_token