- platform: yeelight
  devices:
    192.168.2.245:
      name: bulb salon 1
      transition: 500
      save_on_change: false
      use_music_mode: false
    192.168.2.250:
      name: bulb salon 2
      transition: 500
      save_on_change: false
      use_music_mode: false
    192.168.2.220:
      name: lightstrip sypialnia
      transition: 500
      save_on_change: false
      use_music_mode: false
    192.168.2.225:
      name: lightstrip antek
      transition: 500
      save_on_change: false
      use_music_mode: false

- platform: grouped_light
  name: Bulbs Salon
  entities:
    - light.bulb_salon_1
    - light.bulb_salon_2