- platform: universal
  name: TV Salon
  unique_id: "tv_salon"
  device_class: tv
  children:
    - media_player.philips_65oled707
    - media_player.philips_65oled707_cast
  active_child_template: >
    {% if is_state("select.harmony_activities", "smart") and not is_state("media_player.philips_65oled707_cast", "off") %}
      media_player.philips_65oled707_cast
    {% else %}
      media_player.philips_65oled707
    {% endif %}
  attributes:
    source: media_player.philips_65oled707|source
    source_list: media_player.philips_65oled707|source_list
  browse_media_entity: media_player.philips_65oled707
  commands:
    turn_off:
      service: media_player.turn_off
      data:
        entity_id: media_player.philips_65oled707
    turn_on:
      service: media_player.turn_on
      data:
        entity_id: media_player.philips_65oled707
    select_source:
      service: media_player.select_source
      data:
        entity_id: media_player.philips_65oled707
        source: "{{ source }}"
    media_play:
      service: media_player.media_play
      target:
        entity_id: media_player.philips_65oled707
    media_pause:
      service: media_player.media_pause
      target:
        entity_id: media_player.philips_65oled707
    media_play_pause:
      service: media_player.media_play_pause
      target:
        entity_id: media_player.philips_65oled707
    media_previous_track:
      service: media_player.media_previous_track
      target:
        entity_id: media_player.philips_65oled707
    media_next_track:
      service: media_player.media_next_track
      target:
        entity_id: media_player.philips_65oled707

- platform: universal
  name: TV Goscinny
  unique_id: "tv_goscinny"
  device_class: tv
  children:
    - media_player.sony_kd_55xf8596
    - media_player.sony_kd_55xf8596_cast
  active_child_template: >
    {% if state_attr("media_player.sony_kd_55xf8596", "media_content_id") and not is_state("media_player.sony_kd_55xf8596_cast", "off") %}
      media_player.sony_kd_55xf8596
    {% else %}
      media_player.sony_kd_55xf8596_cast
    {% endif %}
  attributes:
    source: media_player.sony_kd_55xf8596|source
    source_list: media_player.sony_kd_55xf8596|source_list
  browse_media_entity: media_player.sony_kd_55xf8596
  commands:
    turn_off:
      service: media_player.turn_off
      data:
        entity_id: media_player.sony_kd_55xf8596
    turn_on:
      service: media_player.turn_on
      data:
        entity_id: media_player.sony_kd_55xf8596
    select_source:
      service: media_player.select_source
      data:
        entity_id: media_player.sony_kd_55xf8596
        source: "{{ source }}"
    media_play:
      service: media_player.media_play
      target:
        entity_id: media_player.sony_kd_55xf8596
    media_pause:
      service: media_player.media_pause
      target:
        entity_id: media_player.sony_kd_55xf8596
    media_play_pause:
      service: media_player.media_play_pause
      target:
        entity_id: media_player.sony_kd_55xf8596
    media_previous_track:
      service: media_player.media_previous_track
      target:
        entity_id: media_player.sony_kd_55xf8596
    media_next_track:
      service: media_player.media_next_track
      target:
        entity_id: media_player.sony_kd_55xf8596
