- platform: denonavr
  host: !secret denon_hostname
  name: "Denon"
  timeout: 3

- platform: androidtv
  host: !secret mibox_hostname
  adbkey: "~/.android/adbkey"
  name: "MiBox"
  exclude_unnamed_apps: true
  apps:
    com.nvidia.geforcenow: "GeForce NOW"
    com.amazon.amazonvideo.livingroom: "Prime Video"
    com.google.android.youtube.tv: "YouTube"
    eu.hbogo.androidtv.production: "HBO GO"
    com.vimeo.android.videoapp: "Vimeo"
    pl.videostar: "WP Pilot"
    com.spotify.tv.android: "Spotify"
    org.xbmc.kodi: "Kodi"
    tunein.player: "TuneIn"
    pl.idreams.skyforcehdtv: "Sky Force"
    com.leosfortune: "Leo's Fortune"

- platform: braviatv_psk
  host: !secret bravia_hostname
  psk: !secret bravia_psk
  mac: !secret bravia_mac
  amp: true
  android: true
