- platform: denonavr
  host: !secret denon_hostname
  name: "Denon"
  timeout: 3

- platform: androidtv
  host: !secret mibox_hostname
  device_class: "androidtv"
  exclude_unnamed_apps: true
  screencap: false
  apps:
    com.nvidia.geforcenow: "GeForce NOW"
    com.amazon.amazonvideo.livingroom: "Prime Video"
    com.google.android.youtube.tv: "YouTube"
    eu.hbogo.androidtv.production: "HBO Go"
    com.vimeo.android.videoapp: "Vimeo"
    pl.videostar: "WP Pilot"
    com.spotify.tv.android: "Spotify"
    org.xbmc.kodi: "Kodi"
    tunein.player: "TuneIn"
    pl.idreams.skyforcehdtv: "Sky Force"
    com.leosfortune: "Leo's Fortune"
