- platform: rest
  resource: "https://danepubliczne.imgw.pl/api/data/hydro?id=152190050"
  name: "Stan rzeki Bzury"
  state_class : "measurement"
  unique_id: "imgw-hydro-152190050"
  unit_of_measurement: "cm"
  device_class: "distance"
  value_template: "{{ value_json.stan_wody | int }}"
  availability: "{{ value_json is defined }}"
  icon: "mdi:rowing"
  