- platform: wake_on_lan
  name: "stacjonarny"
  host: !secret desktop_hostname
  mac_address: !secret desktop_mac_address
  broadcast_address: 255.255.255.255
  turn_off:
    service: shell_command.stacjonarny_off

- platform: flux
  lights:
    - light.bulbs_salon
    - light.lamp_salon
  name: "Flux"
  start_colortemp: 4400
  sunset_colortemp: 3850
  stop_colortemp: 3300
  mode: mired
  brightness: 255
  transition: 30
  interval: 600

- platform: template
  switches:
    camera_move_up:
      friendly_name: "w górę"
      value_template: "on"
      turn_on:
        service: script.camera_move
        data:
          orientation: "horizontal"
          direction: "up"
      turn_off:
        service: script.camera_move
        data:
          orientation: "vertical"
          direction: "up"

    camera_move_down:
      friendly_name: "w dół"
      value_template: "on"
      turn_on:
        service: script.camera_move
        data:
          orientation: "horizontal"
          direction: "down"
      turn_off:
        service: script.camera_move
        data:
          orientation: "vertical"
          direction: "down"

    camera_move_left:
      friendly_name: "w lewo"
      value_template: "on"
      turn_on:
        service: script.camera_move
        data:
          orientation: "horizontal"
          direction: "left"
      turn_off:
        service: script.camera_move
        data:
          orientation: "horizontal"
          direction: "left"

    camera_move_right:
      friendly_name: "w prawo"
      value_template: "on"
      turn_on:
        service: script.camera_move
        data:
          orientation: "horizontal"
          direction: "right"
      turn_off:
        service: script.camera_move
        data:
          orientation: "horizontal"
          direction: "right"
