- platform: wake_on_lan
  name: "stacjonarny"
  host: !secret desktop_hostname
  mac: !secret desktop_mac_address
  broadcast_address: 255.255.255.255
  turn_off:
    service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown
      input: stacjonarny

- platform: template
  switches:
    ceiling_fan_salon:
      unique_id: "ceiling_fan_salon"
      friendly_name: "Wentylator"
      turn_on:
        service: remote.send_command
        entity_id: remote.salon
        data:
          device: "Wentylator"
          command: "Speed 1"
      turn_off:
        service: remote.send_command
        entity_id: remote.salon
        data:
          device: "Wentylator"
          command: "Stop"

    heater_lazienka:
      value_template: "{{ is_state_attr('climate.thermostat_lazienka', 'temperature', 28) }}"
      turn_on:
        service: climate.set_temperature
        entity_id: climate.thermostat_lazienka
        data:
          temperature: 28
      turn_off:
        service: climate.set_temperature
        entity_id: climate.thermostat_lazienka
        data:
          temperature: 4

    camera_move_up:
      friendly_name: "w górę"
      value_template: "on"
      turn_on:
        service: script.camera_move
        data:
          orientation: "horizontal"
          direction: "up"
      turn_off:
        service: script.camera_move
        data:
          orientation: "vertical"
          direction: "up"

    camera_move_down:
      friendly_name: "w dół"
      value_template: "on"
      turn_on:
        service: script.camera_move
        data:
          orientation: "horizontal"
          direction: "down"
      turn_off:
        service: script.camera_move
        data:
          orientation: "vertical"
          direction: "down"

    camera_move_left:
      friendly_name: "w lewo"
      value_template: "on"
      turn_on:
        service: script.camera_move
        data:
          orientation: "horizontal"
          direction: "left"
      turn_off:
        service: script.camera_move
        data:
          orientation: "horizontal"
          direction: "left"

    camera_move_right:
      friendly_name: "w prawo"
      value_template: "on"
      turn_on:
        service: script.camera_move
        data:
          orientation: "horizontal"
          direction: "right"
      turn_off:
        service: script.camera_move
        data:
          orientation: "horizontal"
          direction: "right"
