- platform: wake_on_lan
  name: stacjonarny
  host: !secret desktop_hostname
  mac_address: !secret desktop_mac_address
  broadcast_address: 255.255.255.255
  turn_off:
    service:
      shell_command.stacjonarny_off

- platform: mqtt
  name: "Light Lamp Salon"
  command_topic: "homeassistant/switch/light-lamp-salon/cmnd/power"
  state_topic: "homeassistant/switch/light-lamp-salon/stat/POWER"
  availability_topic: "homeassistant/switch/light-lamp-salon/tele/LWT"
  payload_available: "Aktywny"
  payload_not_available: "Nieaktywny"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 1
  retain: true

- platform: flux
  lights: light.bulbs_salon
  name: Flux
  start_colortemp: 4400
  sunset_colortemp: 3700
  stop_colortemp: 3000
  mode: mired
  brightness: 255

- platform: template
  switches:
    denon:
      friendly_name: Amplituner
      value_template: "{{ (not is_state('media_player.denon', 'off')) and (not is_state('media_player.denon', None)) }}"
      turn_on:
        service: media_player.turn_on
        entity_id: media_player.denon
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.denon
    playstation:
      friendly_name: PlayStation
      value_template: "{{ (not is_state('media_player.playstation', 'off')) and (not is_state('media_player.playstation', None)) }}"
      turn_on:
        service: media_player.turn_on
        entity_id: media_player.playstation
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.playstation
