- platform: wake_on_lan
  name: 'stacjonarny'
  host: !secret desktop_hostname
  mac_address: !secret desktop_mac_address
  broadcast_address: 255.255.255.255
  turn_off:
    service:
      shell_command.stacjonarny_off

- platform: flux
  lights:
    - light.bulbs_salon
    - light.lamp_salon
  name: 'Flux'
  start_colortemp: 4400
  sunset_colortemp: 3850
  stop_colortemp: 3300
  mode: mired
  brightness: 255
  transition: 30
  interval: 600

# - platform: mqtt
#   name: 'Shelly2 5B2604 Relay 0'
#   state_topic: 'shellies/shellyswitch-5B2604/relay/0'
#   command_topic: 'shellies/shellyswitch-5B2604/relay/0/command'
#   availability_topic: 'shellies/shellyswitch-5B2604/online'
#   unique_id: 'shellyswitch-5B2604-relay-0'
#   payload_on: 'on'
#   payload_off: 'off'
#   payload_available: 'true'
#   payload_not_available: 'false'
#   qos: 1
#   retain: true

- platform: template
  switches:
    denon:
      friendly_name: 'Amplituner'
      value_template: >-
        {% if is_state('media_player.denon', 'on')
           or is_state('media_player.denon', 'playing') %}
          on
        {% elif is_state('media_player.denon', 'off') %}
          off
        {% else %}
          unknown
        {% endif %}
      turn_on:
        service: media_player.turn_on
        entity_id: media_player.denon
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.denon
    playstation:
      friendly_name: 'PlayStation'
      value_template: >-
        {% if is_state('media_player.playstation', 'on')
           or is_state('media_player.playstation', 'playing')
           or is_state('media_player.playstation', 'idle') %}
          on
        {% elif is_state('media_player.playstation', 'off') %}
          off
        {% else %}
          unknown
        {% endif %}
      turn_on:
        service: media_player.turn_on
        entity_id: media_player.playstation
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.playstation

    camera_move_up:
      friendly_name: 'w górę'
      value_template: 'on'
      turn_on:
        service: script.camera_move
        data:
          orientation: 'horizontal'
          direction: 'up'
      turn_off:
        service: script.camera_move
        data:
          orientation: 'vertical'
          direction: 'up'

    camera_move_down:
      friendly_name: 'w dół'
      value_template: 'on'
      turn_on:
        service: script.camera_move
        data:
          orientation: 'horizontal'
          direction: 'down'
      turn_off:
        service: script.camera_move
        data:
          orientation: 'vertical'
          direction: 'down'

    camera_move_left:
      friendly_name: 'w lewo'
      value_template: 'on'
      turn_on:
        service: script.camera_move
        data:
          orientation: 'horizontal'
          direction: 'left'
      turn_off:
        service: script.camera_move
        data:
          orientation: 'horizontal'
          direction: 'left'

    camera_move_right:
      friendly_name: 'w prawo'
      value_template: 'on'
      turn_on:
        service: script.camera_move
        data:
          orientation: 'horizontal'
          direction: 'right'
      turn_off:
        service: script.camera_move
        data:
          orientation: 'horizontal'
          direction: 'right'
