- platform: wake_on_lan
  name: wake_on_lan_stacjonarny
  host: !secret desktop_ip
  mac_address: !secret desktop_mac_address
  broadcast_address: 255.255.255.255
  turn_off:
    service:
      shell_command.stacjonarny_off

- platform: mqtt
  name: "Light Lamp Salon"
  command_topic: "cmnd/sonoff-lamp/power"
  state_topic: "stat/sonoff-lamp/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: flux
  lights: group.bulbs_salon
  name: Flux
  start_colortemp: 4400
  sunset_colortemp: 3700
  stop_colortemp: 2700
  mode: mired
  brightness: 250

- platform: template
  switches:
    denon:
      entity_id: media_player.denon
      friendly_name: Amplituner
      value_template: "{{ (not is_state('media_player.denon', 'off')) and (states.media_player.denon != None) }}"
      turn_on:
        service: media_player.turn_on
        entity_id: media_player.denon
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.denon
    playstation:
      entity_id: media_player.playstation
      friendly_name: PlayStation
      value_template: "{{ (not is_state('media_player.playstation', 'off')) and (states.media_player.playstation != None) }}"
      turn_on:
        service: media_player.turn_on
        entity_id: media_player.playstation
      turn_off:
        service: media_player.turn_off
        entity_id: media_player.playstation