- platform: template
  name: "Dom"
  unique_id: "home"
  condition_template: "{{ states('weather.lowicz') }}"
  temperature_template: "{{ (states('sensor.nettigo_air_monitor_bme280_temperatura') or states('sensor.lowicz_temperatura')) | float }}"
  humidity_template: "{{ (states('sensor.nettigo_air_monitor_bme280_wilgotnosc') or states('sensor.lowicz_wilgotnosc')) | float }}"
  pressure_template: "{{ (states('sensor.nettigo_air_monitor_bme280_cisnienie', rounded=True) or states('sensor.lowicz_cisnienie')) | float }}"
  dew_point_template: "{{ state_attr('weather.lowicz', 'dew_point') }}"
  apparent_temperature_template: "{{ states('sensor.lowicz_temperatura_realfeel') | float }}"
  wind_speed_template: "{{ state_attr('weather.lowicz', 'wind_speed') }}"
  wind_bearing_template: "{{ state_attr('weather.lowicz', 'wind_bearing') }}"
  wind_gust_speed_template: "{{ state_attr('weather.lowicz', 'wind_gust_speed') }}"
  visibility_template: "{{ state_attr('weather.lowicz', 'visibility') }}"
  cloud_coverage_template: "{{ state_attr('weather.lowicz', 'cloud_coverage') }}"
  forecast_daily_template: "{{ state_attr('sensor.pomocnik_prognozy_pogody', 'forecast') }}"
