- platform: template
  name: "Dom"
  unique_id: "home"
  condition_template: "{{ states('weather.lowicz') }}"
  temperature_template: "{{ (states('sensor.nettigo_air_monitor_bme280_temperatura') or states('sensor.lowicz_temperatura')) | float or state_attr('weather.lowicz', 'temperature') }}"
  humidity_template: "{{ (states('sensor.nettigo_air_monitor_bme280_wilgotnosc') or states('sensor.lowicz_wilgotnosc', rounded=True)) | float or state_attr('weather.lowicz', 'humidity') }}"
  pressure_template: "{{ (states('sensor.nettigo_air_monitor_bme280_cisnienie', rounded=True) or states('sensor.lowicz_cisnienie', rounded=True)) | float or state_attr('weather.lowicz', 'pressure') }}"
  dew_point_template: "{{ state_attr('weather.lowicz', 'dew_point') }}"
  apparent_temperature_template: "{{ state_attr('weather.lowicz', 'apparent_temperature') }}"
  wind_speed_template: "{{ state_attr('weather.lowicz', 'wind_speed') | round }}"
  wind_bearing_template: "{{ state_attr('weather.lowicz', 'wind_bearing') }}"
  wind_gust_speed_template: "{{ state_attr('weather.lowicz', 'wind_gust_speed') | round }}"
  visibility_template: "{{ states('sensor.lowicz_widocznosc') }}"
  cloud_coverage_template: "{{ state_attr('weather.lowicz', 'cloud_coverage') }}"
  forecast_daily_template: "{{ state_attr('sensor.lowicz_dzienna_prognoza_pogody', 'forecast') }}"
