- platform: template
  name: "Home"
  unique_id: "home"
  condition_template: "{{ states('weather.accuweather') }}"
  temperature_template: "{{ (states('sensor.nettigo_air_monitor_bme280_temperatura') or states('sensor.dom_temperatura')) | float }}"
  humidity_template: "{{ (states('sensor.nettigo_air_monitor_bme280_wilgotnosc') or states('sensor.dom_wilgotnosc')) | float }}"
  pressure_template: "{{ (states('sensor.nettigo_air_monitor_bme280_cisnienie', rounded=True) or states('sensor.dom_cisnienie')) | float }}"
  dew_point_template: "{{ state_attr('weather.accuweather', 'dew_point') }}"
  apparent_temperature_template: "{{ state_attr('weather.accuweather', 'apparent_temperature') }}"
  wind_speed_template: "{{ state_attr('weather.accuweather', 'wind_speed') }}"
  wind_bearing_template: "{{ state_attr('weather.accuweather', 'wind_bearing') }}"
  wind_gust_speed_template: "{{ state_attr('weather.accuweather', 'wind_gust_speed') }}"
  visibility_template: "{{ state_attr('weather.accuweather', 'visibility') }}"
  cloud_coverage_template: "{{ state_attr('weather.accuweather', 'cloud_coverage') }}"
  forecast_daily_template: "{{ state_attr('sensor.accuweather_pomocnik_prognozy_pogody', 'forecast') }}"
