- platform: template
  name: "Home"
  unique_id: "home"
  condition_template: "{{ states('weather.accuweather') }}"
  temperature_template: "{{ (states('sensor.temperature_outdoor') or state_attr('weather.accuweather', 'temperature')) | float }}"
  humidity_template: "{{ (states('sensor.humidity_outdoor') or state_attr('weather.accuweather', 'humidity')) | float }}"
  pressure_template: "{{ (states('sensor.pressure_outdoor', rounded=True) or state_attr('weather.accuweather', 'pressure')) | float }}"
  dew_point_template: "{{ state_attr('weather.accuweather', 'dew_point') }}"
  apparent_temperature_template: "{{ state_attr('weather.accuweather', 'apparent_temperature') }}"
  wind_speed_template: "{{ state_attr('weather.accuweather', 'wind_speed') }}"
  wind_bearing_template: "{{ state_attr('weather.accuweather', 'wind_bearing') }}"
  wind_gust_speed_template: "{{ state_attr('weather.accuweather', 'wind_gust_speed') }}"
  visibility_template: "{{ state_attr('weather.accuweather', 'visibility') }}"
  cloud_coverage_template: "{{ state_attr('weather.accuweather', 'cloud_coverage') }}"
