sensor.fibaro_fgs223_alarm_level:
  ignored: true
sensor.fibaro_fgs223_alarm_type:
  ignored: true
sensor.fibaro_fgs223_energy_1:
  ignored: true
sensor.fibaro_fgs223_energy_2:
  ignored: true
sensor.fibaro_fgs223_exporting_1:
  ignored: true
sensor.fibaro_fgs223_exporting_2:
  ignored: true
sensor.fibaro_fgs223_heat:
  ignored: true
sensor.fibaro_fgs223_interval_1:
  ignored: true
sensor.fibaro_fgs223_interval_2:
  ignored: true
sensor.fibaro_fgs223_power_2:
  ignored: true
sensor.fibaro_fgs223_power_management:
  ignored: true
sensor.fibaro_fgs223_previous_reading_1:
  ignored: true
sensor.fibaro_fgs223_previous_reading_2:
  ignored: true
switch.fibaro_fgs223_relay_2:
 ignored: true
sensor.fibaro_fgs223_sourcenodeid:
  ignored: true
