sensor.light_salon_alarm_level:
  ignored: true
sensor.light_salon_alarm_type:
  ignored: true
sensor.light_salon_exporting:
  ignored: true
sensor.light_salon_exporting_2:
  ignored: true
sensor.light_salon_heat:
  ignored: true
sensor.light_salon_power_management:
  ignored: true
sensor.light_salon_sourcenodeid:
  ignored: true