substitutions:
  device_name: "BlitzWolf BW-SHP6 [3766EB]"
  device_name_lower: "blitzwolf-bw-shp6-3766eb"
  current_res: "0.00290"
  voltage_div: "940"

esphome:
  name: ${device_name_lower}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret local_domain
  ap:
    ssid: ${device_name}
    password: !secret esphome_password

captive_portal:

logger:

api:
  password: !secret esphome_password

ota:
  password: !secret esphome_password

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    id: button
    internal: true
    pin:
      number: GPIO13
    on_press:
      - switch.toggle: relay

output:
  - platform: gpio
    pin: GPIO00
    inverted: true
    id: led

switch:
  - platform: gpio
    pin: GPIO15
    id: relay
    icon: mdi:power-plug
    name: "${device_name} Relay"
    restore_mode: ALWAYS_ON
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led

  - platform: restart
    name: "${device_name} Restart"

status_led:
  pin:
    number: GPIO02
    inverted: true

sensor:
  - platform: uptime
    name: "${device_name} Last Restart"
    update_interval: 300s
    device_class: "timestamp"
    unit_of_measurement: ""
    filters:
      - lambda: |-
          auto time = id(homeassistant_time).now();
          if (time.is_valid()) {
            return int(time.timestamp) - int(x);
          } else {
            return {};
          }

  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 300s
    device_class: "signal_strength"

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "${device_name} Current"
      unit_of_measurement: "A"
      accuracy_decimals: 3
      device_class: "current"
    voltage:
      name: "${device_name} Voltage"
      unit_of_measurement: "V"
      device_class: "voltage"
    power:
      name: "${device_name} Power"
      unit_of_measurement: "W"
      device_class: "power"
    energy:
      name: "${device_name} Energy"
      unit_of_measurement: "Wh"
      device_class: "energy"
    change_mode_every: 4
