substitutions:
  device_name: "BlitzWolf BW-SHP6 3766EB"
  device_name_lower: "blitzwolf_bw_shp6_3766eb"
  device_hostname: "blitzwolf-bw-shp6-3766eb"
  current_res: "0.00290"
  voltage_div: "940"

esphome:
  name: ${device_name_lower}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_hostname}
  domain: !secret local_domain
  ap:
    ssid: ${device_name}
    password: !secret esphome_password

captive_portal:

logger:

api:
  password: !secret esphome_password

ota:
  password: !secret esphome_password

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    id: button
    internal: true
    pin:
      number: GPIO13
    on_press:
      - switch.toggle: relay

output:
  - platform: gpio
    pin: GPIO00
    inverted: true
    id: led

switch:
  - platform: gpio
    pin: GPIO15
    id: relay
    icon: mdi:power-plug
    name: "${device_name} Relay"
    restore_mode: ALWAYS_ON
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led

  - platform: restart
    name: "${device_name} Restart"

status_led:
  pin:
    number: GPIO02
    inverted: true

sensor:
  - platform: uptime
    id: uptime_sec
    internal: true

  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 300s
    device_class: "signal_strength"

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "${device_name} Current"
      unit_of_measurement: "A"
      accuracy_decimals: 3
      device_class: "current"
    voltage:
      name: "${device_name} Voltage"
      unit_of_measurement: "V"
      device_class: "voltage"
    power:
      name: "${device_name} Power"
      unit_of_measurement: "W"
      device_class: "power"
    change_mode_every: 4

text_sensor:
  - platform: template
    name: "${device_name} Uptime"
    update_interval: 300s
    icon: mdi:timer-outline
    lambda: |-
      auto time = id(homeassistant_time).now();
      if (time.is_valid()) {
        int uptime_seconds = int(id(uptime_sec).state);
        int time_timestamp = int(time.timestamp);
        int uptime_timestamp = { time_timestamp - uptime_seconds };
        auto uptime_text = id(homeassistant_time).now().from_epoch_local(uptime_timestamp).strftime("%Y-%m-%d %H:%M:%S");
        return uptime_text;
      } else {
        return {};
      }