substitutions:
  device_name: "Sonoff S26 182475"
  device_name_lower: "sonoff_s26_182475"
  device_hostname: "sonoff-s26-182475"

esphome:
  name: ${device_name_lower}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_hostname}
  domain: !secret local_domain
  fast_connect: true
  ap:
    ssid: ${device_name}
    password: !secret esphome_password

captive_portal:

logger:

api:
  password: !secret esphome_password

ota:
  password: !secret esphome_password

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    id: button
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay

status_led:
  pin:
    number: GPIO13
    inverted: true

switch:
  - platform: gpio
    id: relay
    pin: GPIO12
    icon: mdi:power-plug
    name: "${device_name} Relay"

sensor:
  - platform: uptime
    name: "${device_name} Uptime"
    unit_of_measurement: days
    update_interval: 300s
    filters:
      - multiply: 0.000011574

  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 300s
