substitutions:
  device_name: "Sonoff S26 [182475]"
  host_name: "sonoff-s26-182475"

esphome:
  name: ${host_name}
  friendly_name: ${device_name}

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret local_domain
  ap:
    ssid: ${device_name}
    password: !secret esphome_password

captive_portal:

logger:

api:
  encryption:
    key: !secret encryption_key

ota:
  platform: esphome
  password: !secret esphome_password

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

time:
  - platform: homeassistant

binary_sensor:
  - platform: gpio
    id: device_button
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay

status_led:
  pin:
    number: GPIO13
    inverted: true

switch:
  - platform: gpio
    id: relay
    pin: GPIO12
    icon: mdi:power-plug
    name: "Przekaźnik"
    restore_mode: RESTORE_DEFAULT_OFF

button:
  - platform: restart
    name: "Uruchom ponownie"
    device_class: "restart"

sensor:
  - platform: uptime
    name: "Ostatni restart"
    type: "timestamp"
    entity_category: "diagnostic"

  - platform: wifi_signal
    name: "Siła sygnału"
    update_interval: 300s
    device_class: "signal_strength"
    entity_category: "diagnostic"
