substitutions:
  device_name: "Wemos D1 mini [1C91EA]"
  device_name_lower: "wemos-d1-mini-1c91ea"

esphome:
  name: ${device_name_lower}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret local_domain
  ap:
    ssid: ${device_name}
    password: !secret esphome_password

captive_portal:

logger:
  baud_rate: 0

api:
  password: !secret esphome_password
  services:
    - service: calibrate
      then:
        - mhz19.calibrate_zero: mhz19_sensor

ota:
  password: !secret esphome_password

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time_sync:
      - component.update: last_restart

uart:
  rx_pin: RX
  tx_pin: TX
  baud_rate: 9600

switch:
  - platform: restart
    name: "${device_name} Restart"

sensor:
  - platform: mhz19
    id: mhz19_sensor
    co2:
      name: "MH-Z19B Carbon Dioxide"
      device_class: "carbon_dioxide"
    temperature:
      name: "MH-Z19B Temperature"
      accuracy_decimals: 1
      device_class: "temperature"
    automatic_baseline_calibration: false
    update_interval: 300s

  - platform: uptime
    id: uptime_sensor
    internal: true

  - platform: template
    name: "${device_name} Last Restart"
    id: last_restart
    device_class: "timestamp"
    accuracy_decimals: 0
    update_interval: never
    lambda: |-
      static float timestamp = (
        id(homeassistant_time).utcnow().timestamp - id(uptime_sensor).state
      );
      return timestamp;

  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 300s
    device_class: "signal_strength"
