substitutions:
  device_name: "Wemos D1 mini [1C91EA]"
  host_name: "wemos-d1-mini-1c91ea"

esphome:
  name: ${host_name}
  friendly_name: ${device_name}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret local_domain
  ap:
    ssid: ${device_name}
    password: !secret esphome_password

captive_portal:

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret encryption_key

ota:
  platform: esphome
  password: !secret esphome_password

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

time:
  - platform: homeassistant

button:
  - platform: restart
    name: "Uruchom ponownie"
    device_class: "restart"

sensor:
  - platform: uptime
    name: "Ostatni restart"
    type: "timestamp"
    entity_category: "diagnostic"

  - platform: wifi_signal
    name: "Sygnał WiFi"
    update_interval: 300s
    device_class: "signal_strength"
    entity_category: "diagnostic"
    