substitutions:
  device_name: "Wemos D1 mini [1C91EA]"
  host_name: "wemos-d1-mini-1c91ea"

esphome:
  name: ${host_name}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret local_domain
  ap:
    ssid: ${device_name}
    password: !secret esphome_password

captive_portal:

logger:
  baud_rate: 0

api:
  password: !secret esphome_password

ota:
  password: !secret esphome_password

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

time:
  - platform: homeassistant
    id: homeassistant_time

button:
  - platform: restart
    name: "${device_name} Restart"
    device_class: "restart"

sensor:
  - platform: uptime
    id: uptime_sensor
    internal: true

  - platform: uptime
    name: "${device_name} Last restart"
    update_interval: 300s
    device_class: "timestamp"
    entity_category: "diagnostic"
    unit_of_measurement: ""
    filters:
      - lambda: |-
          auto time = id(homeassistant_time).now();
          if (time.is_valid()) {
            return time.timestamp - x;
          } else {
            return {};
          }

  - platform: wifi_signal
    name: "${device_name} WiFi signal"
    update_interval: 300s
    device_class: "signal_strength"
    entity_category: "diagnostic"
    