substitutions:
  device_name: "Wemos D1 mini 1C91EA"
  device_name_lower: "wemos_d1_mini_1c91ea"
  device_hostname: "wemos-d1-mini-1c91ea"

esphome:
  name: ${device_name_lower}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_hostname}
  domain: !secret local_domain
  ap:
    ssid: ${device_name}
    password: !secret esphome_password

captive_portal:

logger:

api:
  password: !secret esphome_password

ota:
  password: !secret esphome_password

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

uart:
  rx_pin: RX
  tx_pin: TX
  baud_rate: 9600

switch:
  - platform: restart
    name: "${device_name} Restart"

sensor:
  - platform: mhz19
    co2:
      name: "MH-Z19B Carbon Dioxide"
    temperature:
      name: "MH-Z19B Temperature"
      accuracy_decimals: 1
    automatic_baseline_calibration: false
    update_interval: 300s

  - platform: uptime
    name: "${device_name} Uptime"
    unit_of_measurement: days
    update_interval: 300s
    filters:
      - multiply: 0.000011574

  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 300s
