substitutions:
  device_name: "Wemos Lolin32 [8CBF7C]"
  host_name: "wemos-lolin32-8cbf7c"

esphome:
  name: ${host_name}
  friendly_name: ${device_name}

esp32:
  board: lolin32
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret encryption_key

ota:
  platform: esphome
  password: !secret esphome_password

wifi:
  ssid: !secret wifi_ssid_wpa3
  password: !secret wifi_password
  domain: !secret local_domain
  power_save_mode: high
  ap:
    ssid: ${device_name}
    password: !secret esphome_password

captive_portal:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

esp32_ble_tracker:

bluetooth_proxy:

time:
  - platform: homeassistant
    id: homeassistant_time

button:
  - platform: restart
    name: "Restart"
    device_class: "restart"
  - platform: template
    name: "Kalibruj punkt zero MH-Z19"
    on_press:
      then:
        - mhz19.calibrate_zero: mhz19_sensor
    entity_category: "config"

uart:
  rx_pin: GPIO21
  tx_pin: GPIO22
  baud_rate: 9600

sensor:
  - platform: mhz19
    id: mhz19_sensor
    co2:
      name: "Carbon Dioxide"
      device_class: "carbon_dioxide"
    temperature:
      name: "Temperature"
      accuracy_decimals: 1
      device_class: "temperature"
    automatic_baseline_calibration: false
    update_interval: 300s

  - platform: uptime
    id: uptime_sensor
    internal: true

  - platform: template
    name: "Last restart"
    update_interval: 300s
    device_class: "timestamp"
    entity_category: "diagnostic"
    lambda: |-
      auto time = id(homeassistant_time).now();
      if (time.is_valid()) {
        return time.timestamp - id(uptime_sensor).state;
      } else {
        return {};
      }

  - platform: wifi_signal
    name: "WiFi signal"
    update_interval: 300s
    device_class: "signal_strength"
    entity_category: "diagnostic"

  - platform: internal_temperature
    name: "Device Temperature"

switch:
  - platform: template
    name: "Automatyczna kalibracja MH-Z19"
    optimistic: true
    on_turn_on:
      mhz19.abc_enable: mhz19_sensor
    on_turn_off:
      mhz19.abc_disable: mhz19_sensor
    entity_category: "config"